- website/content/docs/policies/index.mdx
- website/content/docs/policies/migration.mdx
- website/data/docs-nav-data.json
Adds accepted migration policy proposal from #55 :-)
> Add accepted migration policy

- website/content/api-docs/index.mdx
> Document 404 is also an empty list

- website/content/api-docs/secret/ssh.mdx
> Add default_extension_template to ssh docs

- website/package-lock.json
- website/package.json
A new Docusaurus version was released
> update website dependencies

- .goreleaser.yaml
References: #153
Changes:
- Disabled a few OSs that were problematic.
- Corrected the linux file permissions on the binaries.
> Issue-153: Release Pipeline Fixes

- website/src/components/Supporters/index.tsx
References: #285
Changes:
- Corrects Viaccess-Orca's company name.
> Issue 285: Corrected Viaccess-Orca's company name on website.

- website/content/docs/release-notes/2-0-0.mdx
- website/sidebars.ts
Copy the release notes from CHANGELOG.md to the website
Closes: #258
> add 2.0.0-alpha20240329 release notes to website

- website/docusaurus.config.ts
> update website footer

- CONTRIBUTING.md
References: #330
Changes:
- Issue 330: Adding TSC alternate for Wallix.
> Issue 330: Adding TSC alternate.

- CHANGELOG.md
- website/content/docs/release-notes/2-0-0.mdx
- website/package-lock.json
- website/package.json
> add warning about missing UI to changelog

- website/src/components/Releases/index.tsx
- website/src/pages/downloads.tsx
Ignore some more metadata files and add a section for Arch Packages
> update download page logic for new release assets

- vault/logical_system_paths.go
Resolves https://github.com/openbao/openbao/issues/407
1.14.7
> Add system as OperationSuffix to initialize

- website/content/docs/known-issues.mdx
- website/sidebars.ts
Resolves: https://github.com/openbao/openbao/issues/419
// cc: @in0rdr
> Add known issue about SecureBits on Ubuntu 20.04

- vault/external_tests/userpass_binary/ip_token_binding_test.go
> Fix incorrect copyright header in test

- command/login.go
Fix bao cli login success message, as in https://openbao.org/docs/commands/login/#examples .
Resolves #
2.0.1
> Fix bao cli login success message

- sdk/logical/storage_transactions.go
- sdk/physical/transactions.go
Also fixes typo in read-only transaction definition.
> Clarify Rollback and Commit semantics

- website/content/docs/policies/index.mdx
- website/content/docs/policies/migration.mdx
- website/content/docs/policies/release.mdx
- website/sidebars.ts
@JanMa @DanGhita Let me know if I'm missing anything.
> Begin drafting release checklist

- Makefile
- builtin/logical/pki/backend_test.go
- builtin/logical/pki/ca_util.go
- changelog/461.txt
- tools/semgrep/ci/ed25519-pointer.yml
> Fix Ed25519 Pointer in PKI Existing handling

- sdk/helper/keysutil/encrypted_key_storage.go
`EncryptedKeyStorage` is a wrapper used in K/V to ensure that paths (which in the case of K/V may be sensitive) are protected and not disclosed if the underlying (encrypted) storage is compromised. Adding transactions here means that we can modify entries with encrypted path names safely as well.
> Add transaction support to encrypted_key_storage

- sdk/logical/logical_storage.go
`LogicalStorage` is a direct wrapper over a physical backend, only useful for testing when barrier encryption is not desirable. Otherwise, barrier encryption would handle this. Since we want transactions in everything (if the underlying storage mechanism supports it), we want to add it here as well.
> Add transaction support to LogicalStorage

- website/src/components/FAQSection/index.tsx
Simple fix here to add some missing spaces.  I think I followed the contributing guide correctly but if I did not, please let me know.
Resolves #
1.14.7
> Add missing spaces around link in FAQ section.

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/signed-commits.mdx
- website/sidebars.ts
> add signed commits RFC to docs

- website/content/docs/auth/login-mfa/faq.mdx
- website/content/docs/install.mdx
- website/content/docs/platform/k8s/csi/installation.mdx
- website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
- website/content/docs/platform/k8s/injector/installation.mdx
- website/src/pages/index.tsx
This adds missing container registry URLs to the installation page and fixes casing of OpenBao in a couple of places.
> Add container registries

- website/content/docs/install.mdx
> Document the existing package manager for MacOS homebrew

- website/content/docs/install.mdx
Show users how to perform checksum verification during install.
Resolves #537
N/A
> Add checksum verification to installation docs

- website/content/blog/2024-09-23-kickoff.md
- website/content/blog/authors.yml
- website/docusaurus.config.ts
We welcome other contributions to the blog!
----
You know it is a real trend when the [Minnesota Orchestra's Viola Section](https://www.instagram.com/minnorch/reel/DAETgLYJIHb/?hl=en) gets on board with it :D 
I'll probably merge this on Monday as that makes the most sense to me. Should we put a changelog entry to call it out to anyone looking at release notes too?
> Start blog, add kickoff article

- builtin/logical/transit/path_certificates_test.go
- changelog/536.txt
- Adds edge cases to test suite
- Marks changelog entry as feature for better visibility
---
cc: @Gabrielopesantos -- just some minor changes :-)
> Minor improvements to Transit CSR feature

- CONTRIBUTING.md
- MAINTAINERS.md
- website/content/docs/contributing/index.mdx
Also add note from CONTRIBUTING.md as required by Charter and to the website for easy visibility.
See also: https://lists.lfedge.org/g/OpenBao-TSC/topic/announce_roadmap/108738128
> Add Community Roles proposal to MAINTAINERS.md

- api/auth/approle/go.sum
- api/auth/kubernetes/go.sum
- api/auth/ldap/go.sum
- api/auth/userpass/go.sum
- api/go.mod
- api/go.sum
- api/lifetime_watcher.go
- builtin/logical/kubernetes/CHANGELOG.md
- builtin/logical/kubernetes/integrationtest/wal_rollback_test.go
- go.mod
- go.sum
- plugins/database/cassandra/cassandra_test.go
- sdk/go.mod
- sdk/go.sum
- sdk/helper/docker/testhelpers.go
Update from `github.com/cenkalti/backoff/v3` to `github.com/cenkalti/backoff/v4`.
> Update dependency to github.com/cenkalti/backoff/v4

- CONTRIBUTING.md
See also: https://lists.lfedge.org/g/OpenBao-TSC/topic/announce_roadmap/108738128
> Reflect TSC Chair elections

- website/content/blog/2024-10-03-maintainers.md
I think I'll publish this one on Thursday. :-)
> Add blog post on community roles

- Dockerfile
- scripts/docker/Dockerfile
> Bump container versions of Alpine to 3.21

- website/content/blog/2024-10-11-roadmap.md
This announces our roadmap/direction document more formally.
---
I'll publish it on Friday again if nobody objects!
> Add roadmap blog post

- website/content/blog/2024-10-11-roadmap.md
@DanGhita @JanMa -- I got complacent in the new blog post. Any chance I could get a fast review? Thanks!
---
One of the things I think we should try to do at some point is set up a website checking action that comments a link to a temporary version of the website built from the branch, when approved.
> Fix slug & title for roadmap

- physical/raft/raft_test.go
- physical/raft/transaction.go
Ensure all storage operations can be equally performed inside and outside of a transaction; that is, that an individual Put within a transaction does not exceed the limits of a Put outside of a transaction.
> Ensure Raft transaction complies with limits

- website/content/docs/get-started/developer-qs.mdx
Without v2 the old release v1.12.2 gets imported
2.0.3
> import API v2

- website/content/api-docs/secret/ssh.mdx
Small PR to fix the formatting of a markdown table in the SSH docs.
1.14.7
> chore: Fix formatting of SSH docs markdown table

- website/content/blog/2024-10-27-transaction-details.md
Thinking this might be a good one to publish on Monday or Tuesday?
> Add blog detailing raft transactions

- changelog/695.txt
- vault/identity_store.go
- vault/identity_store_entities.go
- vault/identity_store_entities_test.go
> Fix root namespace permission elevation

- builtin/logical/pki/path_tidy.go
- builtin/logical/pki/path_tidy_test.go
This proposes a minor refactor from #665 and adds a new test for ensuring revocation entries are cleaned up as well. 
/cc @fatima2003
> Clean up invalid certs tidy conditions

- CHANGELOG.md
- changelog/502.txt
- changelog/504.txt
- changelog/536.txt
- changelog/699.txt
- website/content/docs/release-notes/2-1-0.mdx
- website/sidebars.ts
This makes various minor cleanups to the changelog entries, adds the release notes to the website, and finally adds the final generated changelog as well.
> v2.1.0-beta20241114 changelog

- .goreleaser-template.yaml
- changelog/641.txt
* Exclude changelog directory from release archive
---------
> Exclude changelog directory from release archive (#641)

- go.mod
- go.sum
* Resolves CVE-2024-51744.
Signed-off-by: Tero Saarni <tero.saarni@est.tech>
> Bump github.com/golang-jwt/jwt/v4 (#691)

- website/content/docs/policies/release.mdx
Let me know if I'm forgetting anything that needs to be documented. :-)
> Update release checklist with v2.1.0-beta20241114 info

- ui/app/components/modal-form/policy-template.js
- ui/app/helpers/all-features.js
- ui/app/routes/vault/cluster/policies/create.js
- ui/app/routes/vault/cluster/policies/index.js
- ui/app/routes/vault/cluster/policy.js
- ui/app/services/download.ts
- ui/app/services/version.js
- ui/app/templates/vault/cluster/policy/show.hbs
Removes the remaining code related to Sentinel in policy menu
Resolves #737
> UI: Remove Sentinel verifications in policy menu

- builtin/logical/pki/path_manage_keys.go
Add block counter and add the block number to the error message (same as https://github.com/openbao/openbao/pull/760)
> PKI: improve error message when parsing PEM bundles (2)

- builtin/logical/pki/path_tidy.go
- sdk/logical/storage.go
In #678, `path_tidy` was refactored to use pagination. Functions like `doTidyCertStore`, `doTidyRevocationStore`, and `doTidyAcme` each contained loops for processing each cert and page. Other files where pagination will be/ has been introduced will also include these loops.
This PR introduces `HandleListPage()` which is a helper for processing paginated storage lists by supporting item-level (itemCallback) and batch-level (batchCallback) processing. 
- `itemCallback` is invoked for each item in the paginated list, enabling fine-grained control over individual entries. 
- `batchCallback` is invoked after processing a full batch, allowing for cumulative operations on the list.
This abstraction reduces redundancy and enhances consistency across paginated operations.
---
Thank you @cipherboy …
> Introduce HandleListPage Helper for Streamlined Pagination

- helper/namespace/namespace_test.go
> Add test for Canonicalize

- physical/raft/raft_autopilot_delegate.go
- vault/external_tests/raft/raft_autopilot_test.go
This adds a missing test for #741
2.2.0
> Test non-voters persist across leadership changes

- website/content/blog/2024-12-11-rfcs-dec-2024.md
This adds a blog post about various in-progress RFCs and areas where we're looking for help with them.
> Add blog post about 2024 RFCs

- .github/pull_request_template.md
> remove target version from PR template

- .github/workflows/verify-commits.yml
- MAINTAINERS.md
See also: https://lists.lfedge.org/g/openbao/topic/openbao_tsc_openbao/109063618
See also: https://lists.lfedge.org/g/openbao/topic/application_to_be_moderator/110182111
/cc @DrDaveD @fatima2003
> Add DrDaveD, fatima2003 to MAINTAINERS.md

- website/content/docs/get-started/developer-qs.mdx
Updated step 4 Bash script to include echo statement to return "Secret written successfully" when the command terminates successfully.
Updated step 5 so the documentation only mentions a return of "Access granted" when looking at the Go code.
> Fix getting started guide

- CHANGELOG.md
- website/content/docs/release-notes/2-1-0.mdx
> Add changelog and release notes for v2.1.1

- CODEOWNERS
See also: https://github.com/openbao/dev-wg/blob/main/notes/2024-11-14.md
> Add initial CODEOWNERS file

- website/content/docs/configuration/storage/filesystem.mdx
- website/content/docs/configuration/storage/in-memory.mdx
- website/content/docs/configuration/storage/index.mdx
- website/content/docs/configuration/storage/postgresql.mdx
- website/content/docs/configuration/storage/raft.mdx
As reported by Branislav Masar on Matrix.
> Fix warnings about external storage

- builtin/credential/ldap/backend.go
- builtin/credential/ldap/path_config.go
- builtin/credential/ldap/path_groups.go
- builtin/credential/ldap/path_users.go
- builtin/credential/radius/path_login.go
- builtin/credential/userpass/path_user_password.go
- builtin/credential/userpass/path_user_policies.go
- builtin/credential/userpass/path_users.go
- changelog/952.txt
This PR adds transaction wrappers for the remaining `credential` paths not covered by #878 
Related #607
> Additional credential transactions

- website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
As I had to retro-discover this setup, let's document it for everyone's sake. It's clearly not complete, but a good starting point I think.
> Docs: Add a simple OIDC keycloak setup example

- website/content/docs/agent-and-proxy/agent/caching/persistent-caches/kubernetes.mdx
- website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
- website/content/docs/platform/k8s/csi/configurations.mdx
- website/content/docs/platform/k8s/csi/examples.mdx
- website/content/docs/platform/k8s/csi/index.mdx
- website/content/docs/platform/k8s/csi/installation.mdx
- website/content/docs/platform/k8s/helm/index.mdx
- website/content/docs/platform/k8s/helm/run.mdx
- website/content/docs/platform/k8s/injector-csi.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/platform/k8s/injector/examples.mdx
- website/content/docs/platform/k8s/injector/index.mdx
- website/content/docs/platform/k8s/injector/installation.mdx
- website/content/partials/kubernetes-supported-versions.mdx
The projects are still unfinished and having the docs visible mostly
leads to confusion-
> disable openbao-k8s and CSI driver docs

- .github/workflows/release.yml
- .goreleaser-template.yaml
- scripts/nightly_tag.sh
This adds nightly release workflows for testing.
Repositories are with the `-nightly` suffix:
- https://github.com/openbao/openbao-nightly
- https://hub.docker.com/repository/docker/openbao/openbao-ubi-nightly/general
- https://hub.docker.com/repository/docker/openbao/openbao-nightly/general
- https://quay.io/repository/openbao/openbao-nightly
- https://quay.io/repository/openbao/openbao-ubi-nightly
By pushing them to a separate repository, we do not clutter the downloads page (https://openbao.org/downloads/) with non-necessary releases (as this fetches releases via the public API, potentially incurring rate limiting). 
All secrets used are unique: a fresh GPG key, fresh cosign keys, and fresh Dockerhub and Quay keys. The Quay token is scoped just to nightly repositories, though the …
> Add nightly release workflow

- website/content/docs/policies/brand.mdx
- website/content/docs/policies/index.mdx
- website/sidebars.ts
Mostly things I've had to reverse engineer. The one piece of policy is a proposal around stickers -- give away stickers with the wordmarks so that people know what the Bao are, and give logo-only stickers to people you've talked to. :-)
> Add initial brand standards policy

- builtin/logical/rabbitmq/path_role_create.go
- changelog/997.txt
Adds transaction wrapper in one rabbitmq method that appears to need
Relates #607
> Add transaction to rabbitmq module

- builtin/credential/approle/path_login.go
- builtin/credential/approle/path_role.go
- changelog/992.txt
Adds transactional storage to the AppRole endpoint funcs.
Relates #607
> Add transactions to AppRole funcs

- builtin/logical/database/path_config_connection.go
- builtin/logical/database/path_creds_create.go
- builtin/logical/database/path_roles.go
- builtin/logical/database/path_rotate_credentials.go
- builtin/logical/database/secret_creds.go
- changelog/995.txt
Adds calls to transaction helpers in the `database` module.
Relates #607
> Add transaction wrappers to database endpoints

- builtin/credential/userpass/path_user_password.go
In fact, err is incorrect and should be  `intErr ` .
Resolves #
> fix: fix the wrong error return value

- .github/actions/set-up-go/action.yml
- .github/workflows/release.yml
- .github/workflows/test-go.yml
> Bump actions/cache to v4, use pinning

- changelog/1042.txt
- ui/app/styles/core/checkbox-and-radio.scss
Signed-off-by: Armin Felder <armin.felder@gmail.com>
Co-authored-by: Azure DevOps Agent <ci-pipeline@none.tld>
-------
> Backport: fix(ui): repairs missing checkmarks, in checkboxes, due to invalid usage of sass-svg-uri (#1042)

- api/sys_raft.go
- command/operator_raft_autopilot_get_config.go
- command/operator_raft_autopilot_set_config.go
- command/operator_raft_autopilot_state.go
- command/operator_raft_listpeers.go
- command/operator_raft_remove_peer.go
- website/content/api-docs/system/storage/raft.mdx
> Backport: cleanup leftover DR Token options (#1018)

- changelog/1013.txt
- vault/identity_store_util.go
Signed-off-by: Pascal Reeb <pascal.reeb@secretz.io>
-------
> Backport: identity: return metadata when listing entity-aliases (#1013)

- CONTRIBUTING.md
- GOVERNANCE.md
See also: https://lists.lfedge.org/g/OpenBao-TSC/topic/tsc_membership_process_vote/111439142
> Officially add TSC membership process

- Makefile
- website/content/api-docs/auth/jwt.mdx
- website/content/api-docs/secret/pki.mdx
- website/content/api-docs/secret/transit.mdx
- website/content/api-docs/system/auth.mdx
- website/content/api-docs/system/mounts.mdx
- website/content/docs/concepts/user-lockout.mdx
- website/content/docs/deprecation/faq.mdx
- website/content/docs/platform/k8s/csi/configurations.mdx
- website/content/docs/release-notes/2-2-0.mdx
- website/content/docs/rfcs/acme-tls-listeners.mdx
- website/content/docs/rfcs/scan-operation.mdx
- website/content/docs/rfcs/transactions.mdx
- website/content/partials/telemetry-metrics/vault/identity/entity/alias/count.mdx
- website/content/partials/telemetry-metrics/vault/raft/peers.mdx
- website/content/partials/telemetry-metrics/vault/rollback/queued.mdx
This PR updates the `make` target `spellcheck` to work on the website content and automatically override the files with any corrections. I have also run the target so any existing typos were fixed. The target could probably be updated to support a path where to check for misspells, such as in code comments.
> website: Fix typos in website content

- vault/logical_system_namespaces.go
Implements JSON Merge Patch for the Namespaces API.
Replaces #1016.
---
@cipherboy I'll keep this in draft state for now as I can't sign-off DCO yet, for internal reasons. ETA is sometime next week... I don't think much else depends on this PR so I'd argue the delay is acceptable. Nevertheless this is ready for review :)
cc: @genelet @driif @klaus-sap @phyrog @voigt
> Add PATCH support to namespaces API

- http/handler.go
- vault/logical_system.go
- vault/logical_system_namespaces.go
- vault/logical_system_namespaces_test.go
- vault/namespaces_store.go
This resolves the following issues related to the namespaces API:
Additional goals:
> Polish namespaces API

- helper/namespace/namespace.go
- helper/namespace/namespace_test.go
- vault/auth.go
- vault/logical_system_namespaces.go
- vault/logical_system_namespaces_test.go
- vault/mount.go
- vault/namespaces_oss.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
Resolves #1040 and the server part of #1063.
/cc @cipherboy @satoqz @wslabosz-reply @voigt @driif
> Add support for child namespaces

- website/src/components/Supporters/index.tsx
Happy to send the internal Slack conversation discussing approval to any GitLab employees.
> Add GitLab to supporters section of homepage

- website/content/blog/2025-03-18-edgex-selects-openbao.md
- website/content/blog/authors.yml
Simple PR to add a blog about how EdgeX Foundry uses OpenBao
> Add EdgeX Selects OpenBao Blog

- website/content/docs/commands/token-helper.mdx
> docs: Correct config file location in token helper docs

- changelog/1129.txt
- vault/identity_store_oidc.go
- vault/identity_store_oidc_test.go
Small additional fix for flakey test.
Relates #1031
> Allow periodicFunc to execute "now"

- website/content/docs/configuration/storage/postgresql.mdx
@cipherboy says the PostgreSQL cookie is baked 😉 
#1137
> Remove Postgres beta warning

- command/config/config.go
> config.go: fix config file filename comment (de-vault)

- vault/mount.go
- vault/mount_test.go
Resolves #1086 
/cc @cipherboy @driif @voigt @wslabosz-reply @satoqz
> implement namespace aware plugin/auth storage

- MAINTAINERS.md
See also: https://lists.lfedge.org/g/openbao/message/213
> Add new moderators: voigt, Gabrielopesantos, karras

- CONTRIBUTING.md
Formal vote wasn't recorded on the mailing list but previous messages reference him being added.
See also: https://lists.lfedge.org/g/openbao-dev-wg/topic/dev_wg_meeting_1_23/110771154
> Add Dave to DevWG voting members

- .github/workflows/mirror.yml
The previously used action turned out to be broken, so provide a simple
alternative workflow.
> fix mirror workflow

- vault/identity_store.go
- vault/identity_store_schema.go
- vault/identity_store_test.go
- vault/identity_store_util.go
Resolves [#1110](https://github.com/openbao/openbao/issues/1110) *Namespace-aware Identity Store*
implementation to conform https://github.com/openbao/openbao/issues/787
---
cc: [@genelet](https://github.com/genelet) @cipherboy @klaus-sap [@satoqz](https://github.com/satoqz) [@phyrog](https://github.com/phyrog)
> Namespace aware identity store #1110

- http/logical_test.go
- vault/namespaces_store_test.go
- vault/testing.go
Resolves [#1020](https://github.com/openbao/openbao/issues/1020)
Added Tests for PR [#1028](https://github.com/openbao/openbao/pull/1028)
---
cc: @cipherboy @klaus-sap [@satoqz](https://github.com/satoqz) [@phyrog](https://github.com/phyrog) @voigt @wslabosz-reply
> Tests for namespace  route resolution - issue #1020

- CHANGELOG.md
- website/content/docs/release-notes/2-2-0.mdx
> Add release notes for v2.2.1 to website

- website/content/docs/rfcs/cel-best-practices.mdx
- website/content/docs/rfcs/index.mdx
- website/sidebars.ts
This RFC seeks to unify behavior and expectations around #753 and #493, plus any upcoming future RFCs around KV or policies.
fyi: @suprjinx @fatima2003 @achetronic
> Add CEL best practices RFC

- website/sidebars.ts
I just added the page to the sidebar. I think, that it is ok to stay in the policies tree for now. I would only create dedicated tree in case the documentation for OSPS grows by a lot. 
Resolves [#10](https://github.com/openbao/dev-wg/issues/10)
> Add OSPS to policies

- website/content/docs/rfcs/cel-jwt.mdx
- website/content/docs/rfcs/index.mdx
This RFC documents CEL usage for JWT/OIDC.
Relates #493
> Add JWT CEL Role RFC

- http/handler_test.go
- http/logical_test.go
- vault/counters.go
- vault/dynamic_system_view_test.go
- vault/expiration_test.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
- vault/namespaces_store_tree.go
- vault/testing.go
- vault/token_store.go
- vault/token_store_test.go
> Hierarchical namespace storage

- vault/auth.go
- vault/auth_test.go
- vault/logical_system.go
- vault/logical_system_namespaces_test.go
- vault/mount.go
- vault/mount_test.go
- vault/router.go
- vault/router_test.go
- vault/testing.go
> Fix `/sys/remount` across namespaces

- CHANGELOG.md
- Makefile
- changelog/1165.txt
- changelog/1172.txt
- changelog/1347.txt
- changelog/1348.txt
- go.mod
- website/content/docs/release-notes/2-3-0.mdx
- website/sidebars.ts
Bump SDK to v2.3.0, add beta to changelog and release notes! 
---
Last one @satoqz!
> Changelog for v2.3.0-beta20250528

- website/content/blog/2025-05-30-namespaces-announcement.md
- website/content/blog/authors.yml
- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
Adding a first draft for an announcement blog post of the new namespaces feature of OpenBao.
> Add ns announcement post

- go.mod
- go.sum
Signed-off-by: Jonas Köhnen <jonas.koehnen@sap.com>
> Bump github.com/ebitengine/purego to v0.8.4 (#1373)

- builtin/credential/jwt/path_config.go
- builtin/logical/pki/backend_test.go
- builtin/logical/pki/chain_test.go
- builtin/logical/pki/crl_test.go
- builtin/logical/pki/path_resign_crls_test.go
- builtin/logical/pki/test_helpers.go
- builtin/logical/ssh/backend_test.go
- builtin/logical/ssh/path_issue_sign.go
- builtin/logical/ssh/path_roles.go
- command/agentproxyshared/cache/testing.go
- command/operator_migrate_test.go
- http/sys_mounts_test.go
- internalshared/listenerutil/tls_acme.go
- physical/crosstest/cross_test.go
- sdk/helper/certutil/types.go
- sdk/helper/keysutil/policy_test.go
- vault/external_tests/storage/crosstest/cross_test.go
Fixes a usage of a couple of deprecated functions/types/packages.
More to come 🙂
> Fix some code deprecations

- changelog/1406.txt
- ui/app/components/namespace-picker.js
- ui/app/components/sidebar/frame.hbs
- ui/app/components/sidebar/nav/access.hbs
- ui/app/routes/vault/cluster.js
- ui/app/routes/vault/cluster/access/namespaces/create.js
- ui/app/routes/vault/cluster/access/namespaces/index.js
- ui/app/services/namespace.js
- ui/app/templates/vault/cluster/access/namespaces/create.hbs
- ui/app/templates/vault/cluster/access/namespaces/index.hbs
- ui/app/templates/vault/cluster/auth.hbs
- ui/config/environment.js
- ui/scripts/test-helper.js
- ui/tests/integration/components/sidebar/nav/access-test.js
- vault/logical_system_helpers.go
> Namespaces UI support

- changelog/1438.txt
- command/server.go
- command/server/config.go
- command/server/config_test.go
This reverts commit c038a659e784162db590c37522a0a2fb3d3a8e60.
See https://github.com/openbao/openbao/pull/1438/files/97847110951a39bb4b78dbcc97fa5c55b3e81d58#r2143718478
> Revert "chore(tls): refactor dev certificates to openbao (#1438)"

- builtin/credential/kerberos/path_login_test.go
See also: https://github.com/openbao/openbao/pull/1434#issuecomment-2966650712
> Move to minio openldap container

- changelog/1209.txt
- changelog/869.txt
---
Backport of https://github.com/openbao/openbao/pull/1440, minus the changes to 794 which I put in the CEL backport.
> Fix changelog entries (#1440)

- changelog/1406.txt
- ui/app/components/namespace-picker.js
- ui/app/components/sidebar/frame.hbs
- ui/app/components/sidebar/nav/access.hbs
- ui/app/routes/vault/cluster.js
- ui/app/routes/vault/cluster/access/namespaces/create.js
- ui/app/routes/vault/cluster/access/namespaces/index.js
- ui/app/services/namespace.js
- ui/app/templates/vault/cluster/access/namespaces/create.hbs
- ui/app/templates/vault/cluster/access/namespaces/index.hbs
- ui/app/templates/vault/cluster/auth.hbs
- ui/config/environment.js
- ui/scripts/test-helper.js
- ui/tests/integration/components/sidebar/nav/access-test.js
- vault/logical_system_helpers.go
* feat(namespaces): add namespace management UI and backend support
* add namespaces to access sidebar
* remove namespace check for routing as feature is always enabled
* fix logical pathInternalUINamespacesRead should return only child namespaces
* fix(namespaces) use current namespace path instead of user root
* fix(namespaces) - link to docs how to use namespaces
* fix assigning userRootNamespace property in namespace service
* fix(test-helper) format keys file output to match ESLint rules
* fix(namespace) reorganize import statements, computed should be imported from @ember/object
* fix(namespace-picker) add optional chaining for userRootNamespace access
* feat(changelog) add release note for Namespaces UI support
* fix(access-test) add 'Namespaces' link to sidebar navigation test …
> Namespaces UI support (#1406)

- changelog/1478.txt
- physical/postgresql/postgresql.go
>  Fix PostgreSQL table creation on replica (#1478)

- changelog/1495.txt
See also: https://github.com/openbao/openbao/security/advisories/GHSA-8f5r-8cmq-7fmq
See also: https://discuss.hashicorp.com/t/hcsec-2025-09-vault-may-expose-sensitive-information-in-error-logs-when-processing-malformed-data-with-the-kv-v2-plugin/74717
See also: https://github.com/go-viper/mapstructure/releases/tag/v2.3.0
See also: https://github.com/go-viper/mapstructure/pull/105
See also: https://github.com/go-viper/mapstructure/commit/ed3f92181528ff776a0324107b8b55026e93766a
Resolves #
> Add changelog entry for sdk/framework vulnerability

- go.mod
- sdk/go.mod
> Bump API to v2.3.1 in core, sdk

- CHANGELOG.md
- go.mod
> Bump sdk to v2.3.1, add changelog to v2.3.0

- website/content/docs/rfcs/authenticated-rekey.mdx
- website/content/docs/rfcs/index.mdx
- website/sidebars.ts
> Add RFC on requiring authenticated rekeys

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/self-init.mdx
- website/sidebars.ts
See also: https://github.com/openbao/openbao/issues/1340
> Add RFC on declarative self-initialization

- MAINTAINERS.md
See also: https://lists.openssf.org/g/openbao/topic/openbao_tsc_openbao/113608426
> Add Geoffrey Wilson to core committers

- website/content/api-docs/secret/pki.mdx
Related PR https://github.com/openbao/openbao/pull/794, Issue https://github.com/openbao/openbao/issues/753
> CEL for PKI API Docs

- website/content/docs/rfcs/external-keys.mdx
- website/content/docs/rfcs/index.mdx
- website/sidebars.ts
See also: https://github.com/openbao/openbao/issues/1319
> Add RFC on External Keys

- vault/barrier_aes_gcm_test.go
- vault/barrier_test.go
- vault/logical_system_rotate.go
- vault/rotate.go
- vault/rotate_test.go
Resolves unresolved conflicts resulting from unfinished rebase.
Additionally validates that the feature branch tests are passing.
> Fix unresolved conflicts in per-namespace sealing poc branch

- website/content/docs/configuration/seal/pkcs11.mdx
- website/content/docs/guides/unseal/pkcs11/securosys.mdx
- website/sidebars.ts
This adds a new section to the website's docs section: Guides.
Also adds a Guide on how to configure OpenBao to Auto-Unseal using Securosys PrimusHSM.
I'm also in the process of create a guide on how to unseal using KMS / the Transaction Broker Service, but this will be handled in a seperate PR.
Resolves #1053
> docs(guides): Securosys PrimusHSM using PKCS#11

- website/content/docs/configuration/seal/pkcs11.mdx
Changes to example to also include AES key generation.
> docs(pkcs11): add AES key generation example

- builtin/credential/userpass/path_login.go
- builtin/credential/userpass/path_login_test.go
- changelog/1628.txt
Backport of https://github.com/openbao/openbao/pull/1628.
> Fix timing leak in userpass auth method (#1628)

- changelog/1613.txt
- vault/policy.go
- vault/policy_store.go
- vault/policy_store_test.go
- vault/request_handling.go
Backport of https://github.com/openbao/openbao/pull/1613.
> Remove policyTypeMap from Policy Store (#1613)

- .github/workflows/release.yml
- LICENSE_DEPENDENCIES.tpl
Backport of https://github.com/openbao/openbao/pull/1607.
> Add release of distribution source tarball (#1607)

- changelog/1594.txt
- vault/core.go
- vault/mount.go
- vault/namespace_store.go
Backport of https://github.com/openbao/openbao/pull/1594.
> Ignore missing mount during namespace deletion (#1594)

- changelog/1629.txt
- vault/external_tests/identity/login_mfa_totp_test.go
- vault/login_mfa.go
Backport of https://github.com/openbao/openbao/pull/1629.
> Address login MFA TOTP reuse vulnerability (#1629)

- CHANGELOG.md
- builtin/credential/jwt/path_cel_login.go
- builtin/credential/jwt/path_cel_login_test.go
- builtin/credential/jwt/path_cel_role.go
- builtin/credential/ldap/backend_test.go
- builtin/credential/ldap/path_login.go
- builtin/credential/radius/path_login.go
- builtin/credential/userpass/path_login.go
- changelog/1625.txt
- changelog/1627.txt
- changelog/1628.txt
- changelog/1629.txt
- changelog/1632.txt
- changelog/1634.txt
- vault/core.go
- vault/expiration_test.go
- vault/external_tests/userpass_binary/ip_token_binding_test.go
- vault/login_mfa.go
- vault/request_handling.go
Cherry pick #1632 and add release notes.
> Prepare for release 2.3.2

- changelog/1652.txt
- ui/app/routes/vault/cluster.js
- ui/app/templates/vault/cluster/unseal.hbs
> change UI message for sealed to 'OpenBao'

- CHANGELOG.md
- website/content/docs/release-notes/2-3-0.mdx
@satoqz This should call out breaking changes as well.
> Add release notes on v2.3.2

- sdk/helper/cidrutil/cidr_test.go
- sdk/helper/compressutil/compress_test.go
- sdk/helper/keysutil/encrypted_key_storage_test.go
- sdk/helper/testcluster/docker/environment.go
- vault/diagnose/helpers_test.go
- vault/external_tests/identity/entities_test.go
- vault/external_tests/plugin/external_plugin_test.go
- vault/external_tests/userpass_binary/ip_token_binding_test.go
- vault/generate_root_test.go
- vault/identity_store_oidc_provider_test.go
- vault/logical_system_namespaces_test.go
- vault/plugin_reload.go
- vault/seal_autoseal_test.go
- vault/token_store.go
See https://github.com/openbao/openbao/issues/1577
> Fix some ineffassign warnings

- builtin/logical/pki/path_issue_sign.go
Resolves - remove duplicated import.
> remove duplicated import of helper/cel

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/namespace-sealing.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
> RFC - Per-namespace sealing

- command/server.go
As reported by Jan Martens on Matrix, the following configuration snippet fails:
> initialize "namespaces" {
>   request "dev" {
>     operation = "create"
>     path = "sys/namespaces/dev"
>   }
>   request "nested" {
>     operation = "create"
>     path = "dev/sys/namespaces/nested"
>   }
> }
This is due to using the same context created in Initialize (which needs the root namespace attached) in the subsequent call to the profile system.
Resolves #
> Fix creation of nested namespaces in self-init

- website/content/docs/audit/index.mdx
> Correctly notate that sys/step-down is audited

- website/content/docs/configuration/seal/pkcs11.mdx
- website/content/docs/guides/unseal/pkcs11/utimaco.mdx
- website/sidebars.ts
Inspired by #1585 by @pree, a slightly lengthy guide on the Utimaco HSMs that I've been able to test with.
> Add guide on PKCS#11 Auto-Unseal with Utimaco HSMs

- builtin/credential/jwt/backend.go
- builtin/credential/jwt/path_oidc.go
- builtin/logical/totp/backend.go
- builtin/logical/totp/path_code.go
- command/agentproxyshared/cache/lease_cache.go
- go.mod
- go.sum
- vault/core.go
- vault/external_tests/identity/login_mfa_totp_test.go
- vault/identity_store.go
- vault/identity_store_oidc.go
- vault/identity_store_oidc_provider.go
- vault/identity_store_oidc_test.go
- vault/login_mfa.go
- vault/request_forwarding_rpc.go
Resolves https://github.com/openbao/openbao/issues/1630
> Replace go-cache with zcache

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/standby-nodes-handle-read-requests.mdx
- website/sidebars.ts
> add RFC for enabling Standby Nodes handle READ Requests

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/opentelemetry.mdx
- website/sidebars.ts
[Preview](https://github.com/adfinis-forks/openbao/blob/rfc-opentelemetry/website/content/docs/rfcs/opentelemetry.mdx)
> Add RFC on OpenTelemetry

- sdk/logical/error.go
- vault/auth.go
- vault/logical_system.go
- vault/logical_system_rotate.go
- vault/mount.go
- vault/rekey.go
- vault/rotate.go
Fix https://github.com/openbao/openbao/issues/1852
> Refactor logical.CodedError to handle variable arguments

- command/plugin_info.go
- website/content/docs/commands/auth/enable.mdx
- website/content/docs/commands/plugin/info.mdx
- website/content/docs/commands/plugin/register.mdx
> Fix incorrect references of `-plugin-version` arg in the documentation

- website/content/blog/2025-09-23-mentorship-program.md
Add a blogpost about OpenBao Mentorship Program.
> Add blogpost about Mentorship Program
