openbao/openbao

- api/client_test.go
- sdk/helper/testcluster/replication.go
These can be run manually with:
```
$ cd api && go test ./...
$ cd sdk && go test ./...
```
Note that, for some reason I haven't yet figured out, the former can be run from the root with `go test github.com/openbao/openbao/api`. but the SDK doesn't run similarly.
Related: #61
> Fix API & SDK failing tests

- .github/workflows/go-dependency-submission.yml
References: #94
Changes:
- Adding a basic GitHub workflow for Golang dependency submission. This will enable basic SBOM generation via GitHub.
> Adding Basic SBOM Support

- builtin/logical/kv/backend.go
- builtin/logical/kv/passthrough.go
- helper/testhelpers/corehelpers/corehelpers.go
- helper/testhelpers/pluginhelpers/pluginhelpers.go
- http/handler_test.go
- http/sys_mount_test.go
- vault/external_tests/plugin/external_plugin_test.go
- vault/logical_system_paths.go
- vault/logical_system_test.go
This switches to the K/V plugin for testing, replacing Consul tests in a lot of places. 
---
Note that this is waiting on #109 to merge as it currently includes that branch in this one. Part of #68; broken up for reviewability.
> Part 16/n - Use kv plugin for tests

- vault/external_tests/identity/aliases_test.go
- vault/identity_store_test.go
As GitHub auth has been removed, we switch to relying on AppRole for various sanity checks.
---
Part of #68; broken up for reviewability.
> Part 17/17 - Move testIdentityStore to use AppRole instead of GitHub

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/cert_util.go
- changelog/50.txt
As discussed upstream, this preserves ordering of the DNS SANs submitted by the caller, giving them control over the ordering on the final certificate. Previously, these were sorted: this resulted in stable ordering (independent of request ordering), but can sometimes result in unexpected behavior if a SAN is unsupported by the browser.
While this is a breaking change (insofar as this can change SAN ordering, which in turn means that there is a potential for newly issued leaf certificates to behave differently when reissued via the same API call), this change also gives more control to the caller to resolve any issues they may currently be running into due to the automated re-ordering.
Thus, on balance, this change is a net benefit to users.
See also: …
> pki: Preserve ordering of submitted SAN names

- builtin/logical/transit/backend_test.go
- builtin/logical/transit/path_datakey.go
- builtin/logical/transit/path_decrypt.go
- builtin/logical/transit/path_encrypt.go
- builtin/logical/transit/path_encrypt_test.go
- builtin/logical/transit/path_rewrap.go
- changelog/85.txt
- sdk/helper/keysutil/policy.go
- website/content/api-docs/secret/transit.mdx
This prohibits the usage of the nonce field entirely, removing it as an API option from Transit. Similarly in the keysutil backend, v1 & v2 keys are forbidden.
Because this completely removes nonce from the APIs, this results in OpenBao issuing a warning about the unknown parameter via the CLI, but does not fail requests. A nil value for nonce will be passed into the SDK, which will then generate a fresh value (for encryption) or use the value inferred from the ciphertext (for decryption).
---
Resolves: #37
> Forbid v1 & v2 convergent keys in Transit

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/cert_util.go
- builtin/logical/pki/fields.go
- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/path_roles.go
- builtin/logical/pki/path_sign_issuers.go
- changelog/76.txt
- sdk/helper/certutil/types.go
- website/content/api-docs/secret/pki.mdx
This adds the ability to set KeyUsage and ExtKeyUsage on roots and intermediates created in OpenBao. This does not add the ability to add KeyUsage or ExtKeyUsage extensions to intermediate CA CSRs as that can be added by the signing CA conditionally.
This allows interoperability with GCP Load Balancers and compiles with CA/BF guidelines. Only DigitalSignature may (optionally) be added to KeyUsage, but no restrictions are placed on ExtKeyUsage or its OIDs.
Resolves: https://github.com/openbao/openbao/issues/60
> Allow setting KeyUsage, ExtKeyUsage on CAs

- builtin/logical/transit/path_decrypt.go
- builtin/logical/transit/path_encrypt.go
- builtin/logical/transit/path_hmac.go
- builtin/logical/transit/path_import.go
- builtin/logical/transit/path_keys.go
- builtin/logical/transit/path_rewrap.go
- builtin/logical/transit/path_rotate.go
- builtin/logical/transit/path_sign_verify.go
- builtin/logical/transit/path_sign_verify_test.go
- sdk/helper/keysutil/lock_manager.go
@Gabrielopesantos started this one in #136 (thank you!!!), but I got a little excited with the tests, so I'll take over from here... :-)
> This PR includes the fix to a bug happening in certain transit operations, sign and verify, where locks weren't being freed as expected which lead to goroutine deadlocks (operations hitting their timeout).
> 
> The deferred call of `Unlock` has been included in the `if` block so that it is only called if `Lock` has been initially called.
>
>EDIT: After doing some additional tests (on other files), it seems there are cases where makes difference between leaving the deferred `Unlock` call to be in the `if` block or outside. Are there any known cases where `Unlock` calls are expected even if `Lock` isn't called?
> 
> Resolves …
>  Transit: Fix bug where locks were not being freed on specific operations - with tests

- api/client.go
- api/client_test.go
- api/env.go
- api/env_test.go
- api/logical.go
- api/plugin_helpers.go
- helper/forwarding/util.go
This PR will allow users to configure OpenBAO with both `VAULT_` and `BAO_` prefixes for environment variables. 
Resolves #66
GA
> fork: Rename Environment Variables

- Makefile
- sdk/framework/testdata/legacy.json
- sdk/framework/testdata/operations.json
- sdk/framework/testdata/operations_list.json
- sdk/framework/testdata/responses.json
As noted in #61, the tests for the `api/` and `sdk/` subpackages were not run; this fixes the failing tests and adds them to the Makefile so this should be prevented in the future. 
Resolves: #61
> Fix running API, SDK tests & vetting

- Makefile
- builtin/credential/jwt/path_oidc_test.go
- builtin/credential/kubernetes/path_login.go
- builtin/logical/kv/path_metadata_test.go
- builtin/logical/pki/acme_errors.go
- builtin/plugin/v5/backend.go
- command/kv_metadata_put_test.go
- helper/pgpkeys/encrypt_decrypt.go
- physical/raft/raft_test.go
- plugins/database/redis/redis.go
- plugins/database/redis/redis_test.go
- scripts/deprecations-checker.sh
- scripts/gofmtcheck.sh
- sdk/helper/certutil/helpers.go
- sdk/helper/docker/testhelpers.go
- vault/activity_log.go
- vault/external_tests/kv/kv_patch_test.go
- vault/identity_store_aliases_test.go
- vault/request_handling.go
- vault/version_store.go
Switch to running external tools directly
Rather than expecting them to be installed locally (via a previous
`go get` operation outside of the repo), use the `go run ...@latest`
pattern. This will download the package (the first time), but not
necessarily install it for the user on a `$PATH`-visible location.
This has the added side effect of ensuring everyone is on the same
version.
---
Also runs `make fmt` to fix a few blank lines. 
---
In particular, on a fresh system with no dependencies, running `make bootstrap` fails for me with:
```
Installing/Updating golang.org/x/tools/cmd/goimports
go: modules disabled by GO111MODULE=off; see 'go help modules'
Installing/Updating github.com/golangci/revgrep/cmd/revgrep
go: modules disabled by GO111MODULE=off; see 'go help modules' …
```
> Run external tools directly

- changelog/184.txt
- ui/app/routes/vault/cluster/oidc-provider.js
- ui/app/templates/vault/cluster/oidc-provider.hbs
- ui/tests/acceptance/oidc-provider-test.js
This fixes the issue when having an Android app authenticate with the OpenBoa OIDC identity provider and having OpenBao in turn authenticate the user with Google OIDC the redirect back to the Android app from OpenBao doesn't work. So after logging in with Google you get correctly redirected to OpenBao but then OpenBAO doesn't redirect back to the app. Chrome (104) on Android would show the logo loading animation forever.
This code was originally developed by @prajnamohan1 while working at Service Planet Rotterdam B.V.. I, Jasper Siepkes, in my capacity of IT Manager at Service Planet Rotterdam B.V. herby grant permission to use this code under the MPL-2.0 license.
Resolves: openbao#184
> Fix OpenBao OIDC followed by Google OIDC not working on Android

- CONTRIBUTING.md
References: #174
Changes:
- Addition of a source-available license policy to contributing.
- Moved DCO section higher in contributing. Added additional language to the section.
> Issue 174: Adding source-available licensing policy to contributing

- .github/workflows/build-vault-ce.yml
- .github/workflows/build.yml
See discussion in https://github.com/openbao/openbao/issues/189:
@naphelps said:
> Per 2024-03-07 community call, the UI will not be shipped as an Alpha release deliverable. This will give the community more time ahead of the future GA release to remediate the remaining issues.
Resolves: https://github.com/openbao/openbao/issues/189
> Temporarily remove UI from release pipelines

- .github/workflows/build-vault-ce.yml
- .github/workflows/build.yml
- .github/workflows/test-go.yml
- builtin/credential/kubernetes/backend_test.go
This removes the remaining unused permissions from the test-go workflow, fixing testing upstream.
See https://github.com/openbao/openbao/actions/runs/8207302185/workflow for an example failing workflow.
> Remove remaining permissions issues in pipelines

- changelog/210.txt
- sdk/helper/shamir/shamir.go
- sdk/helper/shamir/shamir_test.go
This adds several improvements to Shamir's implementation:
1. Use a CS-PRNG with a shuffling algorithm to permute X coordinates in the range [1, 254], removing the need for a later +1 addition later.
2. Panic in the (unreachable) event that the polynomial is evaluated at x == 0; this was already unreachable (and further explicit improvements to shuffling have ensured it remains so), and as it is in a private library function, panicing is an acceptable approach rather than returning an error.
3. Annotate the inverse function to describe multiplications for maintainability.
Resolves: #182
Co-authored-by: @wavefnx
> Improvements to Shamir's implementation

- builtin/logical/transit/backend.go
- builtin/logical/transit/path_backup_test.go
- builtin/logical/transit/path_byok.go
- builtin/logical/transit/path_export.go
- builtin/logical/transit/path_keys.go
- builtin/logical/transit/path_keys_test.go
- changelog/211.txt
- sdk/helper/keysutil/policy.go
- website/content/api-docs/secret/transit.mdx
This adds soft deletion of Transit keys, allowing users to mark keys as
deleted without impacting the ability to backup the key or affecting its
availability to be restored (but preventing all other operations). This
explicitly allows non-exportable keys to be more safely removed, first
via soft deletion (to see if any workloads break and to generally
prevent usage of the key) and then via permanent deletion.
Resolves: #88
---
I also noticed a bug while adding this:
When a RSA keypolicy is generated (and not merely imported),
`RSAPublicKey` is set to `nil`, incorrectly preventing the wrapping of
other keys with this policy. Fix this condition, allowing BYOK export
with destination (wrapping) keys created inside the same Transit
instance.
> Add soft deletion of Transit keys

- builtin/logical/transit/path_export.go
- builtin/logical/transit/path_export_test.go
- builtin/logical/transit/path_keys.go
- changelog/212.txt
- website/content/api-docs/secret/transit.mdx
Transit's export functionality didn't allow choosing the desired output key format and was largely inconsistent about typing. Symmetric keys (and ed25519!) were returned in raw (base64-encoded byte array) format, but RSA and EC keys were returned in their native container formats. This prevents easy interoperability as some tools will not read all of these formats easily; add "der" and "pem" forms for asymmetric keys, to allow native PKIX-typed exports (in typed `SubjectPublicKeyInfo` or `PrivateKeyInfo` containers).
Resolves: #86
> Allow customizing key export format in Transit

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/crl_util.go
- builtin/logical/pki/integration_test.go
- builtin/logical/pki/path_config_urls.go
- builtin/logical/pki/path_fetch_issuers.go
- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/storage.go
- changelog/215.txt
- sdk/helper/certutil/helpers.go
- sdk/helper/certutil/types.go
- website/content/api-docs/secret/pki.mdx
Adds a new AIA URL parameter, delta_crl_distribution_points, which controls where a Delta CRL is located, allowing AIA-aware clients to automatically fetch Delta CRLs as necessary. Unlike other AIA extensions, this extension also appears on the complete CRL, allowing clients with a complete CRL copy to also find the Delta CRL.
Resolves: #84
> Add delta CRL distribution point extension

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/path_issue_sign.go
- changelog/209.txt
- website/content/api-docs/secret/pki.mdx
When a role explicitly allows any key type, certificates of any type or size can be issued via the `pki/sign/:role` endpoint. However, issuing with OpenBao-generated key material isn't possible as OpenBao doesn't know what key type to assign. Thus, introduce new `key_type` and `key_bits` parameters, letting callers opt-in to specific certificate types.
Resolves: #188
> Allow specifying key type during issuance

- builtin/logical/rabbitmq/backend_test.go
- builtin/logical/rabbitmq/path_roles.go
- changelog/224.txt
As reported by @mr-miles, the `rabbitmq` plugin can cause the audit subsystem to crash, due bad response serialization:
> ```
> 2024-03-19T18:50:37.610-0400 [ERROR] TestBackend_RoleReadCrash.core0.audit: panic during logging: request_path=rabbitmq/roles/newrole error="reflect: reflect.Value.Set using unaddressable value"
> ... output elided ...
>   | github.com/openbao/openbao/audit.HashResponse(0xc000739c00, 0xc000ccc6e0, 0x0, {0x0, 0x0, 0x0}, 0x0)
>   | \t/home/cipherboy/GitHub/cipherboy/openbao/audit/hashstructure.go:148 +0x311
>   | github.com/openbao/openbao/audit.(*AuditFormatter).FormatResponse(0xc000760130, {0x33d9068, 0xc0011be210}, {0x33b2b40, 0xc0011be8a0}, {0x0?, 0x0?, 0x0?, 0x0?}, 0xc000304b60)
> ```
This occurs because the output type of the response is bad and includes …
> Use custom serialization of rabbitmq role

- .github/workflows/build.yml
- .github/workflows/changelog-checker.yml
- .github/workflows/ci.yml
- .github/workflows/code-checker.yml
- .github/workflows/dummy-dco-merge-queue.yml
References: #225
Changes:
- Added `merge_queue` triggers to existing GitHub workflows.
- Added a dummy workflow work-around for the DCO bot.
> Issue 225: Add Merge Queue Support

- website/docusaurus.config.ts
We use a custom plugin from upstream to include partials in our MDX docs
which can also contain MDX syntax that needs to be evaluated. The
inclusion needs to happen before the default docusaurus remark plugins
run for them to be able to properly evaluate the contained MDX syntax.
One example where this currently does not work is when we overwrite the
generated anchors of a heading.
**Current status:**
**Fixed status:**
> Fix anchor generation in website partials

- builtin/logical/kubernetes/backend.go
- builtin/logical/kubernetes/integrationtest/wal_rollback_test.go
- tools/semgrep/ci/fmt-printf.yml
This should fix the failing semgrep issues, by updating the kubernetes plugin to use the preferred duration parsing logic and excluding tools/ folders from semgrep results.
> Fix semgrep issues

- builtin/credential/cert/cli.go
- builtin/credential/jwt/cli.go
- builtin/credential/kerberos/cli.go
- builtin/credential/ldap/cli.go
- builtin/credential/token/cli.go
- builtin/credential/userpass/cli.go
- changelog/221.txt
- command/audit_enable.go
- command/delete.go
- command/kv_patch.go
- command/kv_put.go
- command/login.go
- command/operator_generate_root.go
- command/operator_rekey.go
- command/operator_unseal.go
- command/operator_unseal_test.go
- command/patch.go
- command/pki_issue_intermediate.go
- command/pki_reissue_intermediate.go
- command/read.go
- command/ssh.go
- command/transit_import_key.go
- command/write.go
This adds global handling of the `-non-interactive` flag introduced originally for non-interactive MFA support. Most commands with interactive use of `stdin` will either get an empty reader (presumably allowing it to err later) or explicitly err about not being passed input that would otherwise be requested via stdin (e.g., `operator unseal` or `login`).
Resolves: #220
> Add global handling of -non-interactive

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/ca_util.go
- builtin/logical/pki/cert_util.go
- builtin/logical/pki/fields.go
- changelog/201.txt
- website/content/api-docs/secret/pki.mdx
When issuing certificates with /pki_int/sign-verbatim, if the initial CSR contains the extension basicConstraints=CA:FALSE, the issued certificate must include this extension.
Resolves #
https://github.com/openbao/openbao/issues/81
1.14.7
> Fixed issue PKI: Support explicit Basic Constraints isCA=False #81

- website/sidebars.ts
The AWS lambda extension docs were removed, but the sidebar entry is
still there. This blocks the website from being build
> remove obsolete docs sidebar entry

- .github/dependabot.yml
So their dependencies are also kept up to date
> add Dependabot checks for Docs and UI

- .github/workflows/docs-ci.yml
- .github/workflows/docs-deploy.yml
This adds two new workflows to test and deploy the OpenBao website.  Whenever a
PR changes a file in the `website` directory, we try to trigger a full build of
the website. This is the only way to test if everything works. On pushes to main
in the same directory we trigger a build and also deploy it to Github pages.
**Note:** This will have no effect as long as GitHub pages is disabled in the
repository settings.
> add CI pipeline for website

- website/docusaurus.config.ts
Configure the right path to the LF Edge logo displayed in the website footer. This should have been adjusted when preparing the website to be hosted at openbao.org
> fix LF Edge Logo path in footer

- .github/workflows/build.yml
- .github/workflows/release.yml
- .goreleaser.yaml
- changelog/269.txt
Fixes #260 
Allows pushes to Docker hub, ghcr.io, and quay.io.
Needs secrets to be added for Docker and quay.io.
> Allow container upload to multiple registries

- website/content/docs/contributing/code-organization.mdx
- website/content/docs/contributing/index.mdx
- website/docusaurus.config.ts
- website/sidebars.ts
- website/src/pages/index.tsx
This should help to familiarize new contributors to the layout of the repository and what its contents are. Individual areas are not covered in great detail, but instead a high-level overview of areas are present.
---
@naphelps @JanMa -- My general thought was perhaps topical coverage might be interesting? E.g., talking about how OpenBao starts up and unseals, walking through that with links to the code at a point in time? This grows out of date if non-pinned hashes are used (so I'd use pinned ones and drift from `main` over time)... Perhaps when changes are made, the docs could be periodically refreshed and updated?
Thoughts?
> Start a contributing guide with code layout

- sdk/plugin/pb/translation.go
The remote port was not properly propagated to the plugin through grpc.
Resolves #306 
1.14.7
> Fix remote port information in plugins

- changelog/313.txt
- command/base.go
- command/login.go
Resolves #312.
`bao login` used to call the token helper in `get` mode, because it constructs an HTTP client, and the client automatically loads the token. For almost everything that is the right thing to do, but for login, that is the thing that is supposed to retrieve the token, and login itself does not require the token. In fact, `vault login` would erase the token on the client later on.
Calling the token helper in `get` mode is a problem, because if the token helper fails, that blocks the login. But the token helper might fail because it doesn't have a token yet.
The call to `Get` originates here, in the construction of the http client: https://github.com/openbao/openbao/blob/6ef2a6031453b8bdc62fe9cb9511c223323a9e66/command/base.go#L145
That is being called from here: …
> Avoid invoking token helper on login

- website/content/docs/install.mdx
- website/src/components/Releases/index.tsx
- website/src/pages/downloads.tsx
- website/src/pages/index.module.css
This adds a download page to our website. When visiting the site, all releases and their assets are automatically fetched from GitHub and displayed per operating system. The fetched release information is cached in the browser storage for 60 minutes to not cause issues with GitHub API rate limits. 
**Note**: This is mediocre React code at best and has been written with a lot of help by Chat GPT. If anyone reviewing this PR has any React knowledge, suggestions for improvements are very welcome :-) 
As usually, preview of this PR has been deployed to my fork:
https://janma.github.io/openbao/downloads/
Closes: #256 
Alpha
> add download page to website

- changelog/294.txt
- physical/raft/fsm.go
- sdk/physical/testing.go
When a non-empty path is given that ends in a slash and after=., the resulting seek prefix from joining the path and the period has the slash trimmed off. This results in no list results, because this seek prefix lacks the trailing slash and is thus not prefixed by the expected prefix. E.g., for foo/ and after=., we end up with seekPrefix=foo, which doesn't start with our prefix (foo/).
Correctly handle this edge case. This was caught by randomized testing across multiple storage backends.
> Correctly seek in raft's ListPage when after=.

- website/src/pages/downloads.tsx
This adjusts the Website's download page to pull docker images from quay.io
instead of GitHub release assets.
Closes: #327
> download docker images from quay.io

- api/env.go
- changelog/321.txt
- sdk/helper/pluginutil/run_config.go
This adds Upstream (`VAULT_` prefixed) variants of all OpenBao-set variables during plugin startup, allowing plugins compiled for upstream to work with OpenBao.
This should resolve #317 (a discussion).
@DrDaveD Let me know if this works for you!
> Fix compatibility with Vault plugins

- .github/workflows/release.yml
- .goreleaser.yaml
- Dockerfile
References:
Changes:
- Split UBI and Alpine images into two separate container registries.
- Added linux/ppc64le and linux/s390x support.
- Added sbom support to build artifacts.
- Updated Alpine to v3.20 and UBI to v9.4.
- Container registry organization name is now a reference.
- Added additional items to build cache.
> Goreleaser updates

- README.md
References:
Changes:
- Fixed broken readme logo from the website static asset cleanup.
> Fixing broken readme logo.

- website/content/docs/internals/integrated-storage.mdx
The Internals / Integrated Storage page contained legacy Vault information about supporting "several storage options". This commit makes clear that Integrated Storage is the only storage backend in OpenBao.
> Clarify Integrated Storage is only backend

- .github/CODE_OF_CONDUCT.md
- MAINTAINERS.md
References: #358
Changes:
- Swapped Code of Conduct from Hashicorp's to the Linux Foundation project's.
- Added a Maintainers markdown file.
> Issue 358: Swapped Hashicorp's CoC for LF's.

- CONTRIBUTING.md
- MAINTAINERS.md
References:
Changes:
- Adding new maintainers. 
- Adding new Development Working Group.
- Adding new TSC voting member.
https://wiki.lfedge.org/display/OH/2024-06-13+OpenBao+TSC+Meeting
> Adding OpenBao's new maintainers, working group, and tsc voting member.

- .github/workflows/release.yml
- .goreleaser.yaml
GPG signing was broken as `--detach-sign` does not itself take an argument to a file to sign; instead this should be a separate positional argument to the CLI as a whole. This means that stdin was signed instead of the specified file, resulting in bogus signatures.
While the existing cosign signatures work, they require additional calls to rekor to fetch the corresponding certificate used to sign. Mirroring with what OpenTofu does, we can save the certificates directly so that users can verify without additional calls to the rekor network.
Lastly, switch to GitHub-hosted runners to avoid needing to use a self-hosted runner for this release stage.
Thanks to @JanMa and @janosdebugs for their help.
> Fix artifact signing, use default runner

- website/content/docs/concepts/tokens.mdx
Add details on the format of OpenBao tokens, it should hopefully add clear documentation as to one can detect tokens.
The body's format was inferred from:
- https://github.com/openbao/openbao/blob/180024468640acc82eb8dc621f7fd21ce6bfd125/vault/token_store.go#L72-L74
- https://github.com/openbao/openbao/blob/180024468640acc82eb8dc621f7fd21ce6bfd125/vault/token_store.go#L997-L999
Resolves #369 
1.14.7
> docs(token): document the token format

- website/src/components/Releases/index.tsx
We started to generate SBOM and signature files for our release assets
which are currently shown in our download page. This updates our parsing
logic to exclude them and to also handle the new uppercase naming
scheme.
> fix release asset parsing for download page

- .github/workflows/ci.yml
We're running into this open Issue which seems to have been introduced
in version 2.3:
https://github.com/test-summary/action/issues/44
> Downgrade test-summary/action from 2.3 to 2.2

- .github/workflows/release.yml
- .gitignore
- .goreleaser-template.yaml
This splits the release workflow into a matrix, using matrix parallelism to avoid exceeding default disk space (14GB) per OS. If we have too many Linux architectures in the future, we could split by architecture as well.
This should mean that each workflow executes a separate operating system but contributes to a single release draft. We'll need to remember to do manual clean up of releases in the event that a pipeline fails, as currently we'll default to appending to the existing one due to the parallelism.
---
We'll need to recreate the tag after this in order to use this workflow, since `tag` isn't an option in the inputs, only the source branch. We could change that if we desire.
In particular, the issue with this approach is that we have to create a non-draft release right away, …
> Add GOOS matrix to release workflow

- .goreleaser-template.yaml
In #411, we added the `#LINUXONLY#` prefix to the `nfpms` section as it triggered on non-Linux builds; Docker was not thought about as I had removed it for my local repository testing.
This shows the need for a proper staging release area, complete with registries and signing keys.
> Gate Docker steps behind GOOS

- changelog/416.txt
- serviceregistration/kubernetes/service_registration.go
The helm chart creates the service looking for the pod labels `openbao-active=true`. This PR fixes that the label is applied to this name instead of `vault-active`. Additionally it also puts all other labels into `openbao` prefix instead of `vault`.
This is the line in the helm chart has uses as only valid name `openbao-active`: https://github.com/openbao/openbao-helm/blob/main/charts/openbao/templates/server-ha-active-service.yaml#L60
> use openbao instead of vault prefix for kubernetes labels

- changelog/348.txt
- command/base.go
- command/base_predict.go
- command/config/util.go
- command/login.go
- command/login_test.go
- command/server.go
- command/util.go
Previously the token helper might inherit `BAO_ADDR` from the process, but if the address was specified through an `-address` command-line flag, then the token helper would not know the address, or it would use the wrong one. Fix that by propagating the address everywhere, and then setting `BAO_ADDR` explicitly in the token helper's environment.
Resolves #314.
It filled out this by default: 1.14.7
> Pass `BAO_ADDR` to the token helper

- builtin/logical/pkiext/pkiext_binary/pki_cluster.go
- changelog/427.txt
- command/server/server_seal_transit_acc_test.go
- sdk/helper/stepwise/environments/docker/environment.go
- sdk/helper/testcluster/docker/environment.go
- vault/external_tests/misc/misc_binary/recovery_test.go
- vault/external_tests/raft/raft_binary/raft_test.go
- vault/external_tests/userpass_binary/ip_token_binding_test.go
Now that OpenBao has GA'd with v2.0.0, we should update the SDK's docker testing framework to pull that instead of upstream Vault images.
---
This should land ahead of #425 so that consumers of the SDK have the right repository. This ended up being slightly larger than I expected as `sdk/helper/stepwise/environments/docker/environment.go` wasn't updated, but I didn't know how much it was actually used.
> Use quay.io/openbao/openbao in docker tests

- CHANGELOG.md
- changelog/263.txt
Looks like this security issue (#263) missed a changelog entry.
> Add missing changelog for #263

- sdk/logical/storage_transactions.go
- sdk/physical/physical.go
- sdk/physical/transactions.go
This adds interfaces for incremental transactions in sdk/, including to logical.Storage and physical.Backend, eventually allowing support throughout the storage stack.
---
This was split from #292 and was the next required commit to review. 
/cc: @schultz-is
> Add new transaction interfaces to sdk/

- builtin/credential/jwt/path_oidc_test.go
The given authURL is validated against various components that are expected to exist. Per RFC however, the challenge code may have non-word characters (`-` and `_`) when using the alternative URL-safe Base64 encoding mechanism. Expand the regex to handle this case.
See also: https://datatracker.ietf.org/doc/html/rfc7636#section-4.2
> Fix OIDC challenge_code regex in test

- changelog/446.txt
- scripts/docker/docker-entrypoint.sh
In the `docker-entrypoint.sh` script there is an issue with collision between the variable name `BAO_CLUSTER_ADDR` which is used for the redirect interface and for local JSON configuration. Any attempt to set JSON configuration will cause `bao` to fail when attempt to parse what it expects is the cluster interface when it actually JSON configuration.
Therefore, in the lines relating to local JSON configuration the variable has been renamed to `BAO_LOCAL_CONFIG` allowing for users to provide custom JSON configuration without also breaking the cluster address.
Closes #445
> fix: variable name collision in docker-entrypoint

- website/content/docs/platform/k8s/injector/annotations.mdx
The [OpenBao documentation](https://openbao.org/docs/platform/k8s/injector/annotations/) for the injector annotations doesn't match how they are named in [openbao-k8s](https://github.com/openbao/openbao-k8s/blob/main/agent-inject/agent/annotations.go), the TLD should be .org.
Resolves -
1.14.7
> Correct annotations in injector documentation

- CONTRIBUTING.md
As noted via email exchange, OpenHorizon's governance model (wherein WG Chairs are voting members of their TSC) does not apply to OpenBao now that it is started as a separate sub-project under the LF Edge umbrella. Thus, I should not be listed as a TSC representative.
> Remove myself from TSC; clarify Dev WG members

- builtin/logical/pkiext/zlint_test.go
ZLint recently introduced a new check to ensure that the "ou" attribute is not present on TLS CA certificates. Remove this from our test to ensure we can still generate zlint-clean CA certificates from OpenBao.
See also: https://github.com/zmap/zlint/commit/2440571870f32ad14a73eb5f9e74b500c69ecda3
> Fix broken zlint test

- builtin/credential/jwt/path_oidc.go
- builtin/credential/jwt/path_oidc_test.go
- builtin/credential/jwt/path_role.go
- builtin/credential/jwt/path_role_test.go
- changelog/320.txt
- website/content/api-docs/auth/jwt.mdx
This PR adds a configuration option `oauth2_metadata` which is a list of token types that can be returned in metadata.  The list can be any of `access_token`, `id_token`, and `refresh_token`, and when selected they are returned in metadata names `oauth2_access_token`, `oauth2_id_token`, and `oauth2_refresh_token`, respectively.
This option makes it possible for a user to authenticate with bao once and also use the tokens directly from the oauth2 issuer for another purpose.   For example, with some help from a client application to store the refresh token back into a vault secrets plugin like the [Puppet labs oauthapp plugin](https://github.com/puppetlabs/vault-plugin-secrets-oauthapp), from then on access tokens can be read from the secrets plugin and renewed when they expire. 
The new …
> Add oauth2_metadata config option

- physical/raft/fsm.go
- physical/raft/raft.go
- physical/raft/transaction.go
This implements transactions in the Raft backend, using an augmented ApplyLog operation entry. By adding list and get operations (hashing their output state) to the operation log, we can verify state hasn't been modified in parallel by another writer, failing the transaction otherwise.
The current implementation is perhaps inefficient at times: multiple get or list operations over the same path could potentially be collapsed, and all get operations moved to the start of transaction (combing the hashing of multiple entries into a single value, reducing the size of the log on the wire), but this needs to be done carefully. Thus, this work is deferred until later when the current implementation is deemed insufficient.
> Add transactions to Raft backend

- sdk/physical/encoding.go
`StorageEncoding` is a layer which enforces invariants w.r.t. key names in the underlying physical backend. Because it is always added as a layer in the binaries, we need to add transactions to it for a transactional `physical.Backend` to successfully become a transactional `logical.Storage`.
> Add transaction support to StorageEncoding

- physical/raft/fsm.go
- tools/semgrep/ci/splitn-1.yml
This adds a semgrep rule to prevent other instances of the same mistake in the future. The extent of this issue is that
errors.Is(err, physical.ErrTransactionCommitFailure) == false
for actual transaction commit failures, though no code currently conditions around this. The ideal would be that, if an operation should be retried in the event of a transaction commit failure, it theoretically could be. But, other errors during the commit process (not related to consistency) could potentially return a different error and not trigger an automatic retry.
> Correctly split TxErrors

- .github/scripts/verify-commits.jq
- .github/workflows/verify-commits.yml
When a Pr is opened, this workflow checks if all commits made by any of the core
maintainers of OpenBao are verified. This way we can stop enforcing commits via
GitHub branch protection rules for all committers while still ensuring that
maintainer commits need to be signed.
> add workflow to verify maintainer commits

- .github/workflows/ci.yml
This disables the UI tests as the present in-tree UI does not pass tests and significant work is required to fix and update it.
> Disable UI tests

- sdk/logical/storage_inmem.go
- sdk/physical/inmem/inmem.go
This modifies the in-memory physical backend to support transactions in an inefficient manner: clone the entire tree, build an action log, and reply the log against the main tree, validating the state of any touched entries.
A copy-on-write version of go-radix would improve the performance substantially (letting the old version be maintained in the transaction), but since this backend isn't persistent across restarts of OpenBao, it likely is not worth the effort.
> Add in-memory transactional database

- changelog/483.txt
- sdk/physical/cache.go
- sdk/physical/inmem/cache_test.go
Previously, modifications to the storage entry (after performing a put call) could impact the value saved in cache. While likely not common in actual plugins (unless a large number of writes are performed), this pattern is common in tests, to reuse a single Entry for multiple direct write operations.
Switch to creating a deep copied entry to prevent future modifications to the entry from impacting the cache.
> Ensure modifying entries do not affect cache

- changelog/467.txt
- command/commands.go
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
- physical/postgresql/testing.go
- website/content/docs/configuration/storage/postgresql.mdx
- website/sidebars.ts
This starts to re-adds the Postgres storage engine, albeit without transaction support.
We still ~need to add it to the backend binary itself (see e.g. [here](https://github.com/openbao/openbao/blob/0dcb5778fce69c6948d84d2982c3d6aa698ae425/command/server.go#L458-L464) and [here](https://github.com/openbao/openbao/blob/0dcb5778fce69c6948d84d2982c3d6aa698ae425/command/commands.go#L147-L152) and more)~ and, once the testing portion of #292 merges, we'll want to add this to the relevant test suite.
I'm reopening this in case someone else wants to pick up the work to make this Postgres backend transactional while I focus on other portions of the Transactional storage PR series.
---
Related: #270
> Re-add Postgres storage engine

- vault/barrier.go
- vault/barrier_aes_gcm.go
- vault/barrier_aes_gcm_test.go
This extends `SecurityBarrier` into a `TransactionalSecurityBarrier` variant, in which access to the underlying storage (but not the barrier keyring itself!) can be modified in a transaction-aware way.
Note that modifying the barrier keyring within a transaction makes little sense: keyring operations are globally locked and we don't want to rotate to a key used only within a transaction and forked into a different series later. Thus we only support modifications to the barrier keyring outside of the scope of a transaction.
---
This one depends on #443 as we wrap an inmem physical backend for testing, which must be transactional for AES GCM Barrier to become transactional.
> Support transactions in AES-GCM Barrier

- website/content/docs/policies/release.mdx
- Designate a release manager to own the release process, though they can of course delegate items (or, others can volunteer).
- Clarify Go version updating now that we've fixed it in #504.
- Make sure GPG key is uploaded as a release artifact.
- Close the release milestone once done.
> Update release process with v2.0.1 learnings

- website/content/docs/contributing/index.mdx
After a past attendee noticed that recordings were hard to find, it would be good to place these on our website so they're in a central place.
> Add meetings to community website section

- api/output_string.go
- changelog/511.txt
This is a trivial fix to ensure the curl string generated by `buildCurlString()`, invoked by the `-output-curl-string` flag, actually uses the `bao` client instead of attempting to use the `vault` client.
https://github.com/openbao/openbao/issues/510
Next minor release
> fix command `vault print token` to `bao print token` in curl string generated by `buildCurlString()` 

- changelog/512.txt
- vault/core.go
- vault/external_tests/approle/alias_name_panic_test.go
In `aliasNameFromLoginRequest`, a malformed request could be routed to the plugin, which resulted in a `logical.ErrorResponse(...)` being returned. This is a "secret" typed response and not an auth response like we're expecting. We'd thus panic:
> 2024-09-05T08:12:48.249+0100 [INFO]  http: panic serving 127.0.0.1:54504: runtime error: invalid memory address or nil pointer dereference
> goroutine 945 [running]:
> net/http.(*conn).serve.func1()
>         /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:1903 +0xbe
> panic({0x3428060?, 0x649f2d0?})
>         /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
> github.com/openbao/openbao/vault.(*Core).aliasNameFromLoginRequest(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00080c1a0)
> …
> Fix aliasNameFromLoginRequest panic

- website/Dockerfile
- website/Makefile
This adds a new `Dockerfile` and command to enable users to run the website without installing any dependencies locally besides Docker.
In my case, my work laptop lacks `npm` and I've gotten good mileage off of this instead. :-) 
It looks like between v1 and v2 of Docusaurus, they've quit provisioning the `Dockerfile` automatically.
> Add docker-based website viewer

- api/plugin_helpers.go
- changelog/513.txt
- vault/logical_system.go
- vault/logical_system_paths.go
- website/content/api-docs/system/inspect/index.mdx
- website/content/api-docs/system/inspect/request.mdx
- website/sidebarsApi.ts
This adds an endpoint to allow introspection of request data for developers and admins. For instance, one could validate that entity metadata is begin set appropriately or the plugin environment information.
> Add sys/internal/inspect/request endpoint

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/cert_util.go
- builtin/logical/pki/cert_util_test.go
- builtin/logical/pki/fields.go
- builtin/logical/pki/path_issue_sign.go
- builtin/logical/pki/path_roles.go
- builtin/logical/pki/path_root.go
- changelog/515.txt
- sdk/helper/certutil/helpers.go
- sdk/helper/certutil/types.go
- website/content/api-docs/secret/pki.mdx
I went ahead and created a first draft PR.
I let the existing `not_before_duration` but made it so that `not_before` take precedence over it. As with `not_before_duration`, `not_before` has currently no impact on TTL. I am not sure if we should change that. 
Maybe we should even get rid of `not_before_duration` all together?
I noticed there was no existing test in for `getCertificateNotAfter`. Anyway, I added a very simple one for `getCertificateNotBefore`. I need to double-check if we need some other test somewhere else.
Resolves #490 
(I also noticed my editor made some linting on save, hope it's fine; otherwise I can revert it).
> (secrets/pki): add not_before parameter

- website/content/docs/configuration/service-registration/kubernetes.mdx
I was trying out the Kubernetes service registration in openbao and noticed that, setting up,
`VAULT_K8S_NAMESPACE` and `VAULT_K8S_POD_NAME` env's as described in the documentation does not work. We get the below error,
`[WARN]  service_registration.kubernetes: unable to set initial state due to \"namespace\" is unset, will retry`
Fix - These env's have to be replaced with `BAO_K8S_NAMESPACE` and `BAO_K8S_POD_NAME`
> Fix kubernetes Service Registration Guide

- website/content/docs/configuration/service-registration/kubernetes.mdx
Update all occurrences of `vault-` label with `openbao-` in Kubernetes service registration documentation.
PR : https://github.com/openbao/openbao/pull/416 updated all `vault-` prefix with `openbao-`.
This PR updates the documentation for the same.
> Update "vault-" label to "openbao-" in documentation

- changelog/527.txt
- serviceregistration/kubernetes/service_registration.go
When VAULT_ prefixed variables were used, their value would be ignored. As the BAO_ variables likely would be unset, this meant service registration would not succeed.
---
Discovered while looking at #523.
> Fix k8s registration variables

- CONTRIBUTING.md
- website/src/components/Supporters/index.tsx
Per clarification, Michael Maxey intends to resign from the TSC on behalf of Zededa without replacement by Zededa.
See also: https://lists.lfedge.org/g/OpenBao-TSC/topic/zededa_and_open_bao/108134993
---
The change in PCC has also been made.
> Remove Zededa from TSC

- website/content/docs/install.mdx
This PR does the following:
1. Remove one too many '`'.
2. Adds `shell-session`
> Fix typo in install.mdx

- Dockerfile
- changelog/548.txt
- scripts/docker/Dockerfile
This adds a symlink to our Docker images which links `/bin/vault` to
`/bin/bao`. It will fix the issue of a not working Vault/OpenBao agent
injector in our HELM chart.
> add vault symlink to Docker images

- sdk/physical/cache.go
Cache is a layer over the top of the physical storage backend (but below barrier encryption) to reduce strain of repeated read operations on the backend.
We implement transactions by wrapping the underlying physical transaction with a new (empty) cache. This means that we may not have the data locality in oft-read paths, but means that the cache is internally consistent (and that the transaction's cache doesn't need to be merged back into the primary cache). In the future, this could be improved.
> Add transaction support to cache

- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/path_root.go
- changelog/498.txt
This adds transactions to PKI in two places:
1. Root generation
2. Intermediate CA import
Notably, because the CRL rebuild isn't strictly important (though, if it fails, we'd prefer to avoid writing the CAs to storage), we do this in a non-transaction backed storage (if available).
> Add transactions to PKI

- builtin/logical/transit/backend.go
- builtin/logical/transit/path_certificates.go
- builtin/logical/transit/path_certificates_test.go
- builtin/logical/transit/path_encrypt.go
- builtin/logical/transit/path_export.go
- builtin/logical/transit/path_export_test.go
- builtin/logical/transit/path_keys.go
- changelog/536.txt
- sdk/helper/keysutil/policy.go
- website/content/api-docs/secret/transit.mdx
This PR adds two new endpoints to the Transit engine.
- `keys/:name/csr` signs a CSR using the provided key, ensuring the key material stays within Transit. If no CSR is provided, it signs an empty CSR. Otherwise, it signs the provided CSR, replacing its key material with the key material. The key in transit must be a signing key and not be derived.
- `keys/:name/set-certificate` sets the certificate chain for the provided key, ensuring the key material stays within Transit and certificates are managed in one place. It also allows chain updates and rotation, as it will overwrite any existing certificate chain.
Resolves #
1.14.7
> Transit: Support signing a CSR template and setting a certificate chain

- website/content/blog/2024-09-27-profiles.md
- website/content/blog/authors.yml
This blog suggests a new profile-based request system, simplifying application developer's experience by giving them a single endpoint to fetch all secrets configured by their administrator.
---
I'm thinking this might be a good Friday or next Monday topic!
> Add blog post on profiles

- vault/audit.go
- vault/audit_broker.go
- vault/audited_headers.go
- vault/auth.go
- vault/barrier_view.go
- vault/barrier_view_test.go
- vault/core.go
- vault/core_util.go
- vault/expiration.go
- vault/expiration_util.go
- vault/logical_cubbyhole.go
- vault/login_mfa.go
- vault/mount.go
- vault/mount_test.go
- vault/plugin_catalog.go
- vault/policy_store.go
- vault/policy_store_util.go
- vault/router.go
- vault/router_test.go
- vault/token_store.go
- vault/token_store_util.go
This converts `BarrierView` to an interface, updating definitions
everywhere to use it as such. This lets us replace it with two different
structs (`barrierView` and `transacitonalBarrierView`) depending on whether
the underlying physical storage supports transactions.
Note that `BarrierView` is a translation layer, like
`logical.LogicalStorage`, which converts from a `physical.Backend` to a
`logical.Storage` instance. This means `BarrierView` is not itself
stackable.
`BarrierView` is used to ensure mounts only have local access to storage
and cannot impact other plugins' data.
> Support transactions in BarrierView

- builtin/logical/pki/path_manage_issuers.go
- builtin/logical/pki/path_root.go
- sdk/physical/cache.go
This should fix `main` and was caused by the incremental, not-up-to-date merging of the transactional PR series (#292). 
---
There were two separate bugs:
1. Cache invalidation was not occurring correctly. There were two separate bugs here, one which I observed (not invalidating the cache) and the other (race condition on `cacheTransaction.modified`) was only theoretically possible. I'm not sure if concurrent access to the same transaction is something we should deal with, given some backends like PostgreSQL may not support it.
2. Fixing the transaction commit ordering w.r.t. CRL rebuild in PKI. I had forgotten common entries were modified in both, so I've since fixed that. Also, that order may not have worked on PostgreSQL with transactions.
> Fix transactions and PKI interactions

- builtin/logical/pki/acme_authorizations.go
- builtin/logical/pki/acme_challenge_engine.go
- builtin/logical/pki/path_acme_order.go
- changelog/559.txt
When using IPv6 addresses for HTTP-01 challenge in PKI's ACME engine, we needed to correctly template them into the `[bracket]` form.
Resolves: #551
---
TODO:
I reverted the changes to ALPN-01 challenge: per [RFC 8737 section 6.3](https://datatracker.ietf.org/doc/html/rfc8737#name-acme-validation-method), ALPN type only supports domain name. The line identified by @M0NsTeRRR in #551 should only ever be a DNS name and thus doesn't need square bracket special casing.
> Correctly handle IPv6 for HTTP-01

- command/format.go
- command/format_test.go
- command/pki_health_check.go
- command/pki_list_intermediate.go
- command/pki_verify_sign.go
- go.mod
- go.sum
Module `github.com/ghodss/yaml` is not maintained anymore and `sigs.k8s.io/yaml` is a maintained fork that is already pulled by other dependencies.
> Update dependency to sigs.k8s.io/yaml

- api/output_string.go
- changelog/511.txt
* fix command `vault print token` to `bao print token` in curl string generated by `buildCurlString()`
Signed-off-by: btijmen <t.vandenbrink@fairbanks.nl>
* add changelog entry
Signed-off-by: btijmen <t.vandenbrink@fairbanks.nl>
---------
Signed-off-by: btijmen <t.vandenbrink@fairbanks.nl>
2.0.2
> Backport #511 to release 2.0.x

- changelog/512.txt
- vault/core.go
- vault/external_tests/approle/alias_name_panic_test.go
* Fix aliasNameFromLoginRequest panic
In aliasNameFromLoginRequest, a malformed request could be routed to the
plugin, which resulted in a logical.ErrorResponse(...) being returned.
This is a "secret" typed response and not an auth response like we're
expecting. We'd thus panic:
> 2024-09-05T08:12:48.249+0100 [INFO]  http: panic serving 127.0.0.1:54504: runtime error: invalid memory address or nil pointer dereference
> goroutine 945 [running]:
> net/http.(*conn).serve.func1()
>         /opt/hostedtoolcache/go/1.22.6/x64/src/net/http/server.go:1903 +0xbe
> panic({0x3428060?, 0x649f2d0?})
>         /opt/hostedtoolcache/go/1.22.6/x64/src/runtime/panic.go:770 +0x132
> github.com/openbao/openbao/vault.(*Core).aliasNameFromLoginRequest(0xc000806e08, {0x45622f8, 0xc000d6f530}, 0xc00080c1a0)
> …
> Backport #512 to release 2.0.x

- changelog/527.txt
- serviceregistration/kubernetes/service_registration.go
* Fix k8s registration variables
When VAULT_ prefixed variables were used, their value would be ignored.
As the BAO_ variables likely would be unset, this meant service
registration would not succeed.
---------
2.0.2
> Backport #527 to release 2.0.x

- Dockerfile
- changelog/548.txt
- scripts/docker/Dockerfile
This adds a symlink to our Docker images which links `/bin/vault` to
`/bin/bao`. It will fix the issue of a not working Vault/OpenBao agent
injector in our HELM chart.
2.0.2
> Backport #548 to release 2.0.x

- builtin/logical/pki/acme_authorizations.go
- builtin/logical/pki/acme_challenge_engine.go
- builtin/logical/pki/path_acme_order.go
- changelog/559.txt
* Correctly handle IPv6 for HTTP-01 and ALPN-01
When using IPv6 addresses for HTTP-01 and ALPN-01 challenges in PKI's
ACME engine, we needed to correctly template them into the [bracket]
form.
Resolves: #551
---------
2.0.2
> Backport #559 to release 2.0.x

- builtin/logical/ssh/backend_test.go
- builtin/logical/ssh/path_config_ca_test.go
- builtin/logical/ssh/path_issue_sign.go
- builtin/logical/ssh/path_roles.go
- changelog/561.txt
- website/content/api-docs/secret/ssh.mdx
HashiCorp Vault recently released a security vulnerability identifying global issuance without `valid_principals`. They [introduced a new role option](https://developer.hashicorp.com/vault/api-docs/secret/ssh#allow_empty_principals), `allow_empty_principals`, breaking existing users (as it defaults to `false`), but allowing operators to override it on a per-role level.
As evidenced by the extent of the test changes, this is definitely considered a breaking change.
See also: https://discuss.hashicorp.com/t/hcsec-2024-20-vault-ssh-secrets-engine-configuration-did-not-restrict-valid-principals-by-default/70251
See also: https://groups.google.com/g/opensshunixdev/c/RFKeIwNvtn8
See also: https://github.com/openssh/openssh-portable/commit/0a80ca190a39943029719facf7edb990def7ae62
See also: …
> Deny empty valid_principals during SSH issuance

- builtin/logical/ssh/backend_test.go
- builtin/logical/ssh/path_config_ca_test.go
- builtin/logical/ssh/path_issue_sign.go
- builtin/logical/ssh/path_roles.go
- changelog/561.txt
- website/content/api-docs/secret/ssh.mdx
* Deny empty valid_principals during SSH issuance
HashiCorp Vault recently released a security vulnerability identifying
global issuance without valid_principals. They introduced a new role
option, allow_empty_principals, breaking existing users (as it defaults
to false), but allowing operators to override it on a per-role level.
As evidenced by the extent of the test changes, this is definitely
considered a breaking change.
See also: https://discuss.hashicorp.com/t/hcsec-2024-20-vault-ssh-secrets-engine-configuration-did-not-restrict-valid-principals-by-default/70251
See also: https://groups.google.com/g/opensshunixdev/c/RFKeIwNvtn8
See also: https://github.com/openssh/openssh-portable/commit/0a80ca190a39943029719facf7edb990def7ae62
See also: …
> Backport #561 to release 2.0.x

- CHANGELOG.md
- Dockerfile
- scripts/docker/Dockerfile
* secrets/ssh: Deny globally valid certificate issuance without valid_principals or allow_empty_principals override. HCSEC-2024-20 / CVE-2024-7594. (**potentially breaking**) [[GH-561](https://github.com/openbao/openbao/pull/561)]
* docker: add `/bin/vault` symlink to docker images [[GH-548](https://github.com/openbao/openbao/pull/548)]
* api/output_string: Change vault reference to bao. [[GH-511](https://github.com/openbao/openbao/pull/511)]
* core: Fix server panic on AppRole login requests with invalid parameter typing [[GH-512](https://github.com/openbao/openbao/pull/512)]
* secrets/pki: Fix ACME HTTP-01 challenge validation with IPv6 addresses [[GH-559](https://github.com/openbao/openbao/pull/559)]
* serviceregistration/k8s: Fix compatibility with legacy VAULT_-prefixed environment …
> release: v2.0.2

- builtin/logical/kv/path_config.go
- builtin/logical/kv/path_data.go
- builtin/logical/kv/path_delete.go
- builtin/logical/kv/path_destroy.go
- builtin/logical/kv/path_metadata.go
- builtin/logical/kv/path_subkeys.go
- builtin/logical/kv/upgrade.go
- changelog/560.txt
This adds transaction support to the K/V secrets engine, enabling safe modifications to entries stored in the engine, even when operations are canceled partway through.
Notably, this requires careful for ordering: locks should be grabbed before beginning the transaction, otherwise we risk parallel operations causing issues when modifying the same entries, even when we previously would've succeeded.
Resolves: #482
> Add transactions to K/V secrets engine

- website/docusaurus.config.ts
Per October 3rd meeting and TSC mailing list, enable LF Edge's Google Tag Manager / Analytics for insights on blog viewership and for prioritizing documentation updates.
See also: https://lf-edge.atlassian.net/wiki/spaces/OP/pages/15211863/OpenBao+Meetings
See also: https://lists.lfedge.org/g/OpenBao-TSC/topic/openbao_org_lf_s_google/108669761
> Add LF Edge Google Tag Manager analytics

- changelog/292.txt
- physical/crosstest/cross_test.go
- physical/raft/raft_test.go
- sdk/physical/file/file_test.go
- sdk/physical/inmem/cache_test.go
- sdk/physical/inmem/inmem_test.go
- sdk/physical/testing.go
- vault/external_tests/storage/crosstest/cross_test.go
- website/content/docs/rfcs/transactions.mdx
This adds support for interactive transactions across the backend, physical, and plugin storage levels. This will ultimately allow for greater assurance in secrets management operations built on top of OpenBao.
See the RFC in #296 for more detailed information about the design of this change.
Resolves: #296
----
TODO:
<details>
<summary> Benchmarks </summary>
Without transactions (b56dc9c110b7b4f9170a1148d9febcc9a35cef38):
```
$ vault-benchmark run -config=docs/examples/pki/stored/pki-ed25519.hcl 
2024-07-22T12:28:57.564-0400 [INFO]  vault-benchmark: setting up targets
2024-07-22T12:29:01.596-0400 [INFO]  vault-benchmark: starting benchmarks: duration=30s
2024-07-22T12:29:31.604-0400 [INFO]  vault-benchmark: benchmark complete
Target: http://127.0.0.1:8200
op         count   rate …
```
> Transactional storage - Tests & RFC

- changelog/611.txt
- command/debug.go
- command/debug_test.go
- go.mod
- go.sum
As suggested by Wojciech Kocjan, replace insecure archiver (which lacks a patched release except via third-party fork) with standard library. This removes it as a direct dependency.
Notably, our use of archiver was not affected by the vulnerability, as we only created archives (in `bao debug -compress`) and did not read them (except for self-created archives as part of the test suite).
---
Jan, not sure if we'll do a 2.0.3 release before 2.1.0, but figured I'd add the `needs-backport` label in case we do that before 2.1.0 is cut. 
cc @wojciechka
> Replace github.com/mholt/archiver/v3 with stdlib

- changelog/608.txt
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
- physical/postgresql/transaction.go
- sdk/physical/testing.go
- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/transactions.mdx
- website/sidebars.ts
Title says it all :-)
This updates our test suite to test transactions in parallel go routines so that it can conform to PostgreSQL's semantics. Then we add transactions using PostgreSQL's native transactions. I've done some testing with K/V and things seem to behave nicely with the reproducer from #482. 
Resolves: #270
> Add transactional storage to PostgreSQL

- changelog/614.txt
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
- website/content/docs/configuration/storage/postgresql.mdx
When running in certain environments such as Kubernetes via Helm chart, an operator may not necessarily have direct access to the database to create tables manually. Allow OpenBao to create the tables, which is enabled by default if it detects it does not have its tables present.
In the future, this sets us up to handle potential schema migrations, potentially allowing us to scale across multiple tables based on namespaces or other logical shards.
Resolves: #612
> Allow PostgreSQL backend to create tables

- website/src/components/Releases/index.tsx
- website/src/css/custom.css
- website/src/pages/downloads.tsx
This adds both GPG and Cosign signatures to our download page, improves visibility of our container registries, and mentions where to find our GPG key and SBOMs.
----
<details>
<summary> Full-page screenshot </summary>
</details>
Docker switcher:
New download card:
Both the "Download" and label up top ("AMD64 - Debian Package") take you to download the package.
> Improve download page

- website/content/blog/2024-07-25-release-v2-0-0.md
I initially authored this blog post for the LF Edge blog, but realized I never added it here once we started the blog more formally.
See also: https://lfedge.org/announcing-openbao-v2-0-0-the-initial-ga-release/
> Add blog post from v2.0.0 release

- website/content/docs/configuration/storage/raft.mdx
This parameter is specific to the Raft storage backend as PostgreSQL and other backends do not serialize the transaction into a single entity for application.
---
Also clarifies that the old transaction semantic was removed (as it was still mentioned in `max_entry_size`).
> Document max_transaction_size Raft parameter

- sdk/physical/cache.go
```
commit cebec7772febe00f286b9e3ad4f670d7784b2798 (HEAD -> fix-cache-spam-logs-on-txn, origin/fix-cache-spam-logs-on-txn)
Author: Alexander Scheel <ascheel@gitlab.com>
Date:   Sun Oct 13 19:02:38 2024 -0400
Reduce size of cache for each transaction
While transactions should be short-lived, we wish to prevent leaked
transactions from consuming too much memory due to excessive cache
usage. While the cache itself starts empty, a transaction reading and
writing lots of entries could grow the cache: by decreasing by a factor
of DefaultParallelTransactions, we can ensure we only grow the total
memory used by the combined caches by 2x.
commit d3aeb49b73f756f5cb1f39b4ee21568a30ad65fc
Author: Alexander Scheel <ascheel@gitlab.com>
Date:   Sun …
```
> Fix cache spamming logs on transaction creation; limit cache size for transactions

- website/content/blog/2024-10-16-transactions.md
- website/content/docs/rfcs/transactions.mdx
This introduces one of major new features that will be in 2.1.0, trying to see if we can get some users to test it before we release 2.1.0 formally and perhaps also help with broadening the use of transactions in other plugins.
---
I'll probably merge this one on Wednesday.
> Add blog article on transactional storage

- go.mod
- go.sum
- sdk/go.mod
- sdk/go.sum
- sdk/helper/keysutil/encrypted_key_storage.go
- sdk/helper/keysutil/transit_lru.go
- sdk/helper/ocsp/client.go
- sdk/helper/ocsp/ocsp_test.go
- sdk/physical/cache.go
- vault/policy_store.go
This moves to the faster, maintained `golang-lru/v2`. We'll want to be on `v2` if we want to contribute a warm-cache implementation to fix benchmarks in transactions (see #624). 
So far I haven't seen many performance improvements with a warm cache; a later PR will introduce the performance improvements I wanted to see (thanks to Jan for identifying them!).
I will note we don't have many uses of generics in OpenBao so far, but many of these caches are heavily used so I'm inclined to take the faster implementation for them.
> Move to faster golang-lru/v2

- physical/raft/fsm.go
- physical/raft/raft.go
- physical/raft/transaction.go
- sdk/physical/testing.go
I was benchmarking Raft's performance today before and after transactions and noticed that our new implementation was nearly 2.5x slower. This ultimately came down to the `f.db.Update(...)` ordering change in #436. On slower disks, I think the first item is also worthwhile as we can skip several reads from disk. However, on SSDs, this change is much less noticeable.
I still want to do some more testing of this PR before it is ready for general review and also add a few new tests. 
---
```
commit 49092f1fda17ded29919528a8d626298db2b40e8 (HEAD -> track-raft-last-state, origin/track-raft-last-state)
Author: Alexander Scheel <ascheel@gitlab.com>
Date:   Mon Oct 14 19:19:45 2024 -0400
Remove support for legacy getOps
getOps was an operation used by the legacy one-shot transaction; we
leave it …
```
> Improve raft transaction application performance

- website/content/docs/install.mdx
Packages for FreeBSD were added on 2024-09-19: https://www.freshports.org/security/openbao/
Not sure if this trivial update requires an issue?
This is just updating documentation
> Add FreeBSD install instructions.mdx

- .github/workflows/codeql.yml
This should help with [OpenSSF](https://www.bestpractices.dev/en/projects/9126) as it is a static analysis tool, e.g., towards:
>  At least one static code analysis tool (beyond compiler warnings and "safe" language modes) MUST be applied to any proposed major production release of the software before its release, if there is at least one FLOSS tool that implements this criterion in the selected language. [static_analysis]
> Add CodeQL security analysis tooling

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/crl_test.go
- builtin/logical/pki/crl_util.go
- builtin/logical/pki/path_config_crl.go
- builtin/logical/pki/path_revoke.go
- changelog/638.txt
This PR introduces the ability to revoke expired certificates by adding an `allow_expired_cert_revocation` field to the CRL configuration. This field can be globally enabled by the operator in the `config/crl` endpoint, allowing expired certificates to be revoked across the system. The feature is a global setting to ensure deliberate use and avoid unnecessary overhead or arbitrary certificate revocations.
Resolves #459 Vault #27609
1.14.7
___
**TO DO LIST**
> PKI - Allow revocation of expired certificates

- .github/workflows/release.yml
- .goreleaser-template.yaml
- Makefile
- changelog/639.txt
Fixing https://github.com/openbao/openbao/issues/599
Fix : 
1. Make the conf files as `type: config` in .goreleaser-template.yaml so the files are not overwritten during rpm upgrade.
2. Add a new target in makefile to build rpm locally
> Don't override conf files in OpenBao binaries

- builtin/credential/jwt/cli.go
- builtin/credential/jwt/path_config.go
- builtin/credential/jwt/path_oidc.go
- builtin/credential/jwt/path_oidc_test.go
- builtin/credential/jwt/path_role.go
- changelog/319.txt
- website/content/api-docs/auth/jwt.mdx
- website/content/docs/auth/jwt/index.mdx
This adds support for OIDC device flow on top of pr #318.  #318 has to be committed first and all its changes are included here.  If you'd like to see just the changes compared to that pr, see [my own pr 1](https://github.com/DrDaveD/openbao/pull/1).
Device flow has several advantages over direct callback mode:
1. There's no need to configure allowed redirect uris for the client.
2. There's no need to configure firewalls to allow the Authorization Server to call back to Vault.
3. There's no need for the Authorization Server to recognize the CA cert for Vault.
4. The URL that the user sees is simpler.
So it's worth having device flow even compared to direct callback mode, although direct callback mode is good when Authorization Servers don't support device flow.
Device flow is enabled with …
> Add oidc device flow after direct flow

- builtin/logical/pki/path_tidy.go
- builtin/logical/pki/path_tidy_test.go
- website/content/api-docs/secret/pki.mdx
- Adds web docs for `revoked_safety_buffer`.
- Refactor of auto-tidy to better handle revoked vs non-revoked certificates.
- Fix test case to better handle differences in timing.
This is a follow-up to #653. :-) 
/cc: @fatima2003
> Revoked safety documentation, minor fixes

- changelog/682.txt
- scripts/docker/docker-entrypoint.sh
There's been a mixup between BAO_CLUSTER and BAO_REDIRECT environment
variables.
Closes: #681
> fix docker-entrypoint env vars

- changelog/622.txt
- sdk/physical/error.go
- vault/auth.go
- vault/auth_test.go
- vault/external_tests/metrics/core_metrics_int_test.go
- vault/logical_system.go
- vault/logical_system_helpers.go
- vault/logical_system_test.go
- vault/mount.go
- vault/mount_test.go
- vault/plugin_reload.go
- vault/rollback_test.go
- website/content/docs/rfcs/split-mount-tables.mdx
- website/sidebars.ts
OpenBao has an implicit limit on the number of mounts much lower than can theoretically fit in memory: the maximum Raft storage entry size. In practice, the use of compression (after applying JSON encoding to the table) lets us achieve a higher than expected limit. Large deployments can still hit this limit.
By relying on the newly introduced transactional storage, we can split the mount table into separate entries (one per mount), which is performant due to reuse of the bbolt transaction. This lets us avoid the lower entry limit at the risk of hitting the higher transaction limit in the future.
However, this also makes updates scoped: only reading or writing a large number of entries (combining path + hash) and then committing will hit this limit; individual mount additions or …
> Split mount tables with transactions

- ui/lib/core/addon/components/doc-link.js
- ui/lib/core/addon/components/external-link.js
- ui/lib/pki/README.md
- ui/tests/integration/components/form-field-label-test.js
Some links in `README` & code comments was referring to hashicorp documentation.
Small part of #74
Add missing changes in #669
> UI: Update documentation links & fix `Doc link renders` test

- go.mod
- go.sum
This PR resolves CVE-2024-51744 in github.com/golang-jwt/jwt/v4. Although this vulnerability does not directly affect OpenBao's security, it is flagged in vulnerability scans. Upgrading the dependency will resolve this issue in future scans.
> Bump github.com/golang-jwt/jwt/v4

- vault/core_test.go
- vault/deadlock_test.go
This lets us disable the deadlock tests in the race detector, keeping CI clean. Unfortunately, the deadlock library in use does not allow atomic control over these values and doesn't recommend setting them post-startup. While running in tests are serial and nothing else is executing in the process state, it is not ideal but workable. This code is not used in production.
> Move deadlock tests to separate file

- builtin/credential/jwt/path_login_test.go
This PR attempts to address a flaky test in the "Run Go tests with data race detection / test-go (11)" group, which contains a time-sensitive test case that frequently fails with the following error:
```
=== FAIL: builtin/credential/jwt TestLogin_Leeways (4.33s)
path_login_test.go:1091: [test 19: not yet valid custom nbf leeway using exp with no clock_skew_leeway jws: {<nil> 0xc00040e840 map[]  [] <nil> map[]}] expected token not valid yet error, got : true
```
The test seems to use unnecessarily strict timing constraints.
https://github.com/openbao/openbao/blob/737c77b39b1ba28dd474141d5a20bab48c41ca20/builtin/credential/jwt/path_login_test.go#L1065-L1066
It checks that a JWT with an expiration set 7 seconds in the future is invalid when the not-before leeway is 5 seconds. I think this …
> Adjust the JWT leeway tests to reduce time sensitivity.

- changelog/690.txt
- vault/core.go
- vault/logical_system_raft.go
- vault/raft.go
Rather than storing a map of serverID->answer (and generating fully random challenge answers), use HKDF on the serverID and a secret key to create challenge answers using only a single constant-space key. HKDF should be at least as fast as the underlying RNG source and this ensures we do not incur any additional memory per request to this un-authenticated endpoint.
See also: https://discuss.hashicorp.com/t/hcsec-2024-26-vault-vulnerable-to-denial-of-service-through-memory-exhaustion-when-processing-raft-cluster-join-requests/71047
> Compute raft peer bootstrap challenge via HKDF

- Dockerfile
- changelog/701.txt
Per https://hub.docker.com/r/redhat/ubi9-minimal/tags, this is now available.
> Update to UBI 9.5

- go.mod
- sdk/go.mod
~This replace directive meant that anyone consuming our SDK would have to include a similar replace directive in their own go module. This is an unfortunate side-effect of how modules work and undesirable in general; remove this.~
This may be incorrect, see: https://github.com/openbao/openbao/pull/705#pullrequestreview-2435486904
> Bump sdk to api/v2@v2.1.0

- .goreleaser-template.yaml
- Makefile
This also adds a new Makefile target, `goreleaser-check`, to validate the configuration is working.
> Update goreleaser config version to 2

- go.mod
- go.sum
This earlier commit lacks metrics (which we do not emit as they were introduced after us), but also lacks the extra original (archived) bbolt dependency that causes RISC-V builds to fail. This dependency was included because subsequent commits added support for migrating from the archived bbolt to the supported etcd fork, which we do not need as we never relied on the earlier fork.
> Revert to github.com/hashicorp/raft-boltdb/v2@v2.0.0-20210421194847-a7e34179d62c

- .goreleaser-template.yaml
- Makefile
This fixes a bug in the goreleaser status that failed to wire up the prerelease status correctly. In particular, it meant that our beta release was both tagged as latest in GitHub but also in container images. 
See: 
https://github.com/openbao/openbao/blob/d45510adab420b225d6bf2c166b197358cfc4a0b/.github/workflows/release.yml#L144
Note the `_RELEASE_` that wasn't present earlier.
> Fix goreleaser prerelease status

- .goreleaser-template.yaml
- Makefile
This also adds a new Makefile target, `goreleaser-check`, to validate
the configuration is working.
> Update goreleaser config version to 2 (#709)

- changelog/695.txt
- vault/identity_store.go
- vault/identity_store_entities.go
- vault/identity_store_entities_test.go
* Clone entity on modifications
When modifying an entity, ensure we clone the MemDB copy so that we do
not accidentally modify the value stored in the underlying MemDB. This
ensures we can use it as a staging area and only persist changes on
explicit upsert.
* Clone entity on invalidations
While the invalidation should only be triggered when storage is
writable, if we have an alias invalidation on an entity, we should
only modify the in-memory entity on upsert, not when the alias is
added to the entity. This ensures failures to upsert do not cause a
modified entity to be present in memory.
--------- …
> Fix root namespace permission elevation (#695)

- Dockerfile
- changelog/701.txt
* Update to UBI 9.5
Per https://hub.docker.com/r/redhat/ubi9-minimal/tags, this is now
available.
---------
> Update to UBI 9.5 (#701)

- changelog/611.txt
- command/debug.go
- command/debug_test.go
- go.mod
- go.sum
* Replace github.com/mholt/archiver/v3 with stdlib
As suggested by Wojciech Kocjan, replace insecure archiver (which lacks
a patched release except via third-party fork) with the standard
library's archive/tar and compress/gzip. This removes it as a direct
dependency.
Notably, our use of archiver was not affected by the vulnerability, as
we only created archives (in `bao debug -compress`) and did not read
them (except for self-created archives as part of the test suite).
---------
> Replace github.com/mholt/archiver/v3 with stdlib (#611)

- .goreleaser-template.yaml
- Makefile
* Validate both Linux and non-Linux release files
* Correctly wire prerelease with GH Actions
This fixes tagging of container images to only push the full tags if it
is a pre-release. This also addresses creating the release on GitHub as
pre-release because the workflow used a different environment variable
name.
---------
> Fix goreleaser prerelease status (#713)

- builtin/credential/jwt/path_login_test.go
This PR continues from #698, which did not fully resolve the CI time sensitivity issue.
In this change, I've "unrolled" the table-driven test so that each sub-test now uses the current time at the beginning of each-sub-test. This replaces the previous approach where tests ran relative to the time during table initialization at the start of the whole test case, which caused frequent failures due to strict timing sensitivity.
The diff looks larger than the actual changes. Although I (mostly) kept the formatting of the table and only added the function calls, it's showing as if the entire section was modified.  I made one change that might be hard to spot in the diff: I removed [this](https://github.com/openbao/openbao/blob/758e24181d71c93a75dc36cd0d17ab55d485c475/builtin/credential/jwt/path_ …
> Get current time in each JWT leeway subtest

- sdk/physical/testing.go
1. Added Dedicated sync.WaitGroup for Writers, Readers, and Listers:
Purpose: To ensure proper synchronization and orderly completion of all goroutines.
Benefit: This approach ensures that the main test function waits for all writer, reader, and lister goroutines to complete before proceeding, preventing race conditions and ensuring consistent test results.
2. Removed time.Sleep Calls:
Purpose: To eliminate arbitrary delays and rely on proper synchronization mechanisms.
Benefit: This makes the code more efficient and predictable. Using sync.WaitGroup ensures that the test waits for all necessary operations to complete without relying on fixed sleep durations, which can be unreliable and lead to flaky tests.
2.1: The sleep times weren't 100% stable and could cause scenarios where the …
> [fix][inmem - Occasional logging after test finishes #702] 

- website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
Not only a single certificate, but a bundle of PEM-encoded certificates may be passed
Resolves #
2.1.1
> PKI: clarify usage of set-signed command

- website/docusaurus.config.ts
- website/public/robots.txt
- website/src/pages/index.tsx
This updates various website metadata and adds a robots.txt to link the sitemap to hopefully make it more visible to search engines. 
Sadly I don't think the `<link rel="sitemap" ... />` is actually working though: https://docusaurus.io/docs/api/docusaurus-config#headTags
> Update website metadata

- website/src/pages/downloads.tsx
When switching releases, add a version to the query string (replacing the current state) so users can send the link to the exact version to others. Additionally, add a warning box to prerelease versions.
> Add version to download page, prerelease warning

- builtin/credential/cert/backend_test.go
- builtin/logical/pki/backend_test.go
- builtin/logical/pki/crl_test.go
- builtin/logical/pki/path_resign_crls_test.go
- builtin/logical/pki/path_roles_test.go
- command/agent/cert_end_to_end_test.go
- vault/identity_store_oidc_provider_test.go
This PR replaces the domain name `myvault.com` with `example.com` in tests as recommended in [RFC2606](https://datatracker.ietf.org/doc/html/rfc2606#section-3). 
> **Reserved Example Second Level Domain Names**
>    The Internet Assigned Numbers Authority (IANA) also currently has the
>    following second level domain names reserved which can be used as
>    examples.
>         example.com
>         example.net
>         example.org
This is grep's output after these changes:
```
/builtin/credential/cert/test-fixtures/generate.txt:3:vault write pki/root/generate/exported common_name=myvault.com ttl=438000h ip_sans=127.0.0.1
./builtin/credential/cert/test-fixtures/generate.txt:20:vault write pki/root/generate/exported common_name=myvault.com ttl=438000h max_ttl=438000h ip_sans=127.0.0.1 …
```
> Replace myvault.com with example.com in tests

- website/content/docs/commands/print.mdx
The current version (v2.0.2) of Openbao tokens are expected to match the following regexp: `[sbr]\.[a-zA-Z0-9]{24,}` as documented in [the website](https://openbao.org/docs/concepts/tokens/) and [github source](https://github.com/openbao/openbao/blob/release/2.0.x/website/content/docs/concepts/tokens.mdx)
> fit token to openbao format

- changelog/736.txt
- vault/logical_system.go
- vault/logical_system_paths.go
- vault/policy_store.go
- website/content/api-docs/system/policies.mdx
- website/content/api-docs/system/policy.mdx
The `sys/policies/acl/*` paths allow arbitrary structuring of policies into paths, e.g., `a/b` and `a/c` may exist. Using path prefixes are useful e.g., when structuring policies into pipelines or projects or tenants. However, policy listing was not capable of only listing policies under a given prefix. So results for `d/e`, `default`, and `root` would also be returned, even if only policies under `a/` were desired by the caller.
Support list operations on prefixes to allow callers to view policies only under some root prefix.
> Allow listing prefixed policies

- builtin/logical/pki/path_manage_issuers.go
Add block counter and add the block number to the error message
> PKI: improve error message when parsing PEM bundles

- builtin/logical/pki/backend_test.go
- builtin/logical/pki/fields.go
- builtin/logical/pki/path_tidy.go
- builtin/logical/pki/path_tidy_test.go
- changelog/678.txt
- website/content/api-docs/secret/pki.mdx
This PR modifies the tidy process to use pagination, allowing certificates to be processed in increments rather than loading the entire set into memory at once. This would be particularly helpful when the cert store contains millions of certs. The default page size is 1000 certificates but custom page sizes can be specified via a flag `page_size`. Minimum page size is 5 and to default to previous behavior, i.e., skip out on pagination, set `page_size=-1` or any negative int.
Partly resolves #271
1.14.7
---
> Add pagination to tidy 

- api/client_test.go
- sdk/helper/certutil/certutil_test.go
- vault/diagnose/tls_verification.go
`tlsConfig.RootCAs.Subjects` deprecated and removed from test files.
```
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || …
```
> Remove usage of deprecated .Subjects() in test files

- changelog/741.txt
- command/operator_raft_join.go
- http/util.go
- physical/raft/raft.go
- physical/raft/raft_autopilot.go
- physical/raft/raft_autopilot_delegate.go
- physical/raft/raft_autopilot_promoter.go
- physical/raft/snapshot_test.go
- vault/logical_system_raft.go
- website/content/api-docs/system/storage/raft.mdx
- website/content/docs/commands/operator/raft.mdx
- website/content/docs/concepts/integrated-storage/index.mdx
This PR reimplements a previous enterprise feature to allow nodes to join a Raft cluster as non-voting members. Nodes can now be configured as non-voters by either using the new `-non-voter` flag in the `operator raft join` command or by setting the existing configuration option `retry_join_as_non_voter`.
- Introduced a `-non-voter` flag to the `operator raft join` command.
- Enhanced join logic to support both the `-non-voter` flag and the pre-existing `retry_join_as_non_voter` configuration option.
- Updated relevant Raft implementation files and improved the handling of non-voter joins.
- Added documentation updates to reflect these changes.
Closes: #578
> Allow Nodes to Join the Raft Cluster as Non-Voters

- website/content/blog/2024-11-29-release-v2-1-0.md
This will make it a little easier to find installation instructions for anyone hitting the blog post.
> Add download link to v2.1.0 blog post

- api/logical.go
- builtin/logical/kv/backend.go
- builtin/logical/kv/passthrough.go
- builtin/logical/kv/passthrough_test.go
- builtin/logical/kv/path_metadata.go
- changelog/763.txt
- command/commands.go
- command/kv_scan.go
- command/scan.go
- command/scan_test.go
- http/cors.go
- http/logical.go
- http/logical_test.go
- sdk/framework/openapi.go
- sdk/helper/stepwise/stepwise.go
- sdk/logical/request.go
- vault/acl.go
- vault/acl_test.go
- vault/logical_system.go
- vault/policy.go
- vault/policy_test.go
- website/content/api-docs/secret/kv/kv-v1.mdx
- website/content/api-docs/secret/kv/kv-v2.mdx
- website/content/docs/concepts/policies.mdx
- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/scan-operation.mdx
- website/sidebars.ts
This introduces support for recursive listing (scans):
- A new `SCAN` operation (including handler type, HTTP verb, and `GET` fallback via `?scan=true`) for notating APIs which return all data.
- A new `SCAN` capability, allowing operators to selectively allow the above (due to the default-deny policy).
- `SCAN` operation support within KV, recursively listing all entries under the given prefix.
- `SCAN` support in the API and CLI. 
Resolves: #549
---
/cc @dirsigler
> Add scan operation for recursive listing

- website/content/docs/platform/k8s/helm/run.mdx
Added a warning before the port forwarding section for the UI that the UI needs to be built from the source code and is not available on the helm chart.
This section of the docs is a 1:1 copy of the vault documentation while the expectation is that we build our own ui from source to use. (which is fine) Its not mentioned here in any manner and its easy to just think that everything will work just like vault I think its important to at least make the information that its not the case at the moment easily readable
> added warning for ui on helm chart

- ui/app/components/sidebar/frame.hbs
- ui/app/components/sidebar/user-menu.hbs
- ui/app/styles/app.scss
- ui/app/styles/components/sidebar.scss
Change the black sidebar to green to match the coloring on our Website
and in the logo.
2.2.0
> ui: change sidebar coloring to match OpenBao colors

- go.mod
- go.sum
- sdk/go.mod
- sdk/go.sum
- sdk/plugin/grpc_backend_test.go
I am adding a dependency to CEL in the SDK module as part of #794. During this process, I found that updating the `hashicorp/go-plugin` dependency causes `sdk/plugin/grpc_backend_test.go` to break due to changes in the function signature of `TestPluginGRPCConn`.
The updated version of `TestPluginGRPCConn` introduces an additional bool parameter that determines whether metrics should be enabled during the plugin's execution. As a result, the existing calls to this function in `grpc_backend_test.go` need to be updated to include this new parameter. The tests pass when the bool is enabled/disabled, the difference is in the logging details.
**Example disabling the bool and running `TestGRPCBackendPlugin_Version`:** 
```
Running tool: /usr/local/go/bin/go test -timeout 30s -run …
```
> Update hashicorp/go-plugin version in SDK

- Makefile
- scripts/build.sh
While we don't release our builtin plugins as external, it would be good to ensure we don't break compatibility with them. This starts by adding a script to build all builtin plugins as external.
> Allow building external plugins via Makefile

- Dockerfile
- changelog/826.txt
This avoids writing the devroot token, allowing the image to be used from a read-only base.
Resolves: #356
> Add -dev-no-store-token to container entrypoint

- .github/dependabot.yml
Resolves: #694 
---
I hadn't realized this would also handle container images, which would be nice for avoiding the issues with our October release.
> Add dependabot for go.mod, container images

- .github/dependabot.yml
This is because API and SDK updates should be synchronized via `make sync-deps` and not done directly.
> Prune dependabot to only handle main module

- website/content/api-docs/secret/pki.mdx
Nit in the pki docs. The parameter `not_before` is not formatted to be part of a list even though points before and after are in list format.
> Nit: Put not_before in bullet point format.

- changelog/750.txt
- command/server.go
- http/sys_init.go
- http/sys_rekey.go
- vault/barrier.go
- vault/barrier_aes_gcm.go
- vault/barrier_aes_gcm_test.go
- vault/barrier_test.go
- vault/core.go
- vault/external_tests/api/sys_rekey_ext_test.go
- vault/external_tests/raft/raft_test.go
- vault/external_tests/sealmigration/testshared.go
- vault/generate_root_test.go
- vault/ha.go
- vault/init.go
- vault/keyring.go
- vault/keyring_test.go
- vault/rekey.go
- vault/rekey_test.go
- vault/seal.go
- vault/seal_autoseal.go
- vault/seal_testing.go
- vault/seal_testing_util.go
- vault/testing.go
- website/content/api-docs/system/rekey.mdx
This cleans up various legacy migrations that should have already occurred by Vault 1.14 (the last Vault release users should've come from).
1. Remove support for pre-keyring barrier encryption
2. Remove support for legacy (direct) Shamir seals.
3. Better enforce that there are only zero or one StoredShares (root keys). 
4. Simplify all references of master->root keys. This was partially renamed but never completed, which makes evaluating the key hierarchy in code much more difficult.
> Clean up legacy keyring code

- website/content/api-docs/secret/pki.mdx
Nit: `basic_constraints_valid_for_non_ca` is indented under `user_ids` which makes it look like it's a sub-property or related field.
> Nit: fix indentation for basic_constraints_valid_for_non_ca

- .github/dependabot.yml
This might address why `actions/cache` is out of date in `.github/actions/set-up-go/action.yml` despite dependabot saying there is nothing to do: https://github.com/openbao/openbao/pull/163#issuecomment-2599722950
> Attempt to add reusable components to dependabot

- Dockerfile
Bumps alpine from 3.20 to 3.21.
---
updated-dependencies:
- dependency-name: alpine dependency-type: direct:production update-type: version-update:semver-minor ...
Backport of: https://github.com/openbao/openbao/pull/831
> Bump alpine from 3.20 to 3.21 (#831)

- website/content/docs/plugins/plugin-authors-guide.mdx
- website/sidebars.ts
This PR adds a Plugin Author Guide to the website under docs/plugins. 
The guide is intended to:
- Document the reasoning behind certain design decisions and behaviors in plugins.
- Provide a clear understanding of the design logic for current and future plugin authors.
- Assist new contributors in getting up to speed quickly.
- Ensure consistency and clarity in contributions to the project.
Resolves #749
> Create plugin authors guide

- changelog/921.txt
- helper/testhelpers/corehelpers/corehelpers.go
- vault/logical_system.go
- vault/logical_system_test.go
When protected mounts were disallowed from tuning in b9a5a137c002211328cc90d9d7e92170d0d86908, only TTL status was present in the tune interface at the time. Tuning HMAC status of request/response in the audit log was not present but makes sense for all mounts, even protected mounts.
Thanks to @jficz for pair coding this!
Resolves: #474
---
Live coding video: https://youtu.be/lr7_YmEIOro
> Allow tuning HMAC status on protected mounts

- api/sys_mounts.go
- changelog/935.txt
- command/healthcheck/healthcheck.go
- command/pki_health_check.go
- command/pki_health_check_test.go
When `bao pki health-check` runs on a non-PKI mount, we see results like:
ca_validity_period
------------------
status             endpoint                        message
------             --------                        -------
invalid_version    /auth/userpass/users/issuers    This health check requires Vault 1.11+ but an earlier version of Vault Server was contacted, preventing this health check from running.
which isn't correct: we are running on a non-PKI mount, not on an invalid version of Vault or OpenBao.
As reported by @pgnd on Matrix.
> Ensure pki health-check errs on non-pki mounts

- changelog/937.txt
- physical/raft/raft_autopilot.go
- vault/raft.go
When we attempt Raft keyring rotation on a standby-less node, the minimum follower index is zero, which differs from our actual present index. This means the new keyring is never accepted, unless we later join a standby node. Instead, always apply the new keyring if we have no followers.
We keep the rotation to prevent the 30-year certificates from expiring before a follower is added (or, more likely, in the event of bad system clock at initial rotation).
Thanks to @pgnd for reporting on Matrix.
Resolves: #936
> Fix noisy warn in Raft key rotation

- website/content/docs/contributing/packaging.mdx
- website/content/docs/install.mdx
- website/sidebars.ts
Also introduces a packaging guide addressing common questions.
As reported by @pgnd on Matrix.
> Add warning to compiling from source guide

- internalshared/configutil/no_pkcs11.go
- internalshared/configutil/pkcs11.go
Using an implicit CGO tag means that the PKCS#11 build must succeed on musl (which it likely won't); move it to an explicit tag and let the build fail with a rather cryptic error if CGO is not specified but the hsm build tag is:
```
==> Building bao...
../../../go/pkg/mod/github.com/openbao/go-kms-wrapping/wrappers/pkcs11/v2@v2.0.0-20250114185509-3fa7a3d31521/pkcs11_client.go:55:22: undefined: pkcs11.Ctx
../../../go/pkg/mod/github.com/openbao/go-kms-wrapping/wrappers/pkcs11/v2@v2.0.0-20250114185509-3fa7a3d31521/pkcs11_client.go:278:53: undefined: pkcs11.SessionHandle
../../../go/pkg/mod/github.com/openbao/go-kms-wrapping/wrappers/pkcs11/v2@v2.0.0-20250114185509-3fa7a3d31521/pkcs11_client.go:278:79: undefined: pkcs11.ObjectHandle
../../../go/pkg/mod/github.com/openbao/go-kms-wrapping/wrappe …
```
> Add explicit hsm build tag

- .github/workflows/release.yml
- .goreleaser-template.yaml
- changelog/940.txt
Resolves: #739 
---
I think I will setup a new repository, `openbao-nightly`, which mirrors `openbao` and launches nightly release builds... I'll provision fresh keys, fresh access tokens, and fresh repositories (with `-nightly` suffix) which contain updated nightly releases.
Thoughts?
> Add UI to release workflow

- changelog/958.txt
- vault/diagnose/tls_verification.go
Resolves #957
`bao operator diagnose` skips listener TLS checks for unix-socket based listeners
> Fix unix-listener in `bao operator diagnose`

- builtin/logical/transit/path_byok.go
- builtin/logical/transit/path_certificates.go
- builtin/logical/transit/path_config_keys.go
- builtin/logical/transit/path_encrypt.go
- builtin/logical/transit/path_import.go
- builtin/logical/transit/path_keys.go
- builtin/logical/transit/path_keys_config.go
- builtin/logical/transit/path_rotate.go
- builtin/logical/transit/path_trim.go
- changelog/956.txt
Adds transactional storage to `transit` functions with read+write operations
Relates #607
> Add transactions to transit functions

- audit/format.go
- audit/format_test.go
- audit/hashstructure.go
- audit/hashstructure_test.go
- changelog/887.txt
Audit logging uses reflection to write the hashed value of logged fields to a copy of the log data.  That write is inherently problematic.  If the log data contains structs, the struct fields may be "unaddressable" with reflection and the write attempt causes a panic, (as described here): https://github.com/openbao/openbao/issues/478
The fix is to remove all structs by marshalling the data to json and back.  This creates a deep copy where all structs/fields have been converted to maps/keys.
Prior to this fix, the hashing code made a copy of the data structure to be logged, and uses reflection to walk the copy and hash the data.
Because the fix uses the json unmarshalled copy, many of the data types get changed, (like structs to maps).  So the fixed code must walk both the original and the …
> Modify audit logging to handle nested structs without panicing

- changelog/816.txt
- command/server.go
- command/server/config.go
- command/server/config_custom_response_headers_test.go
- command/server/config_telemetry_test.go
- command/server/config_test.go
- command/server/config_test_helpers.go
- command/server/listener_test.go
When using the official container image with no arguments, OpenBao automatically invokes the server as:
```
$ bao server -config=/openbao/config "$@"
```
A user might reasonably expect to mount their configuration into /openbao/config, perhaps using a filename ending in .hcl or .json, and pass -config=/openbao/config/my-config.hcl, not expecting it to be auto-loaded. When this occurs, a strange error such as:
> bind: cannot assign requested address
occurs, because there are two identical listener configurations with the same address: one from loading the configuration file as a directory and one from adding it as a config file.
We opt to not entirely deduplicate arguments, but do warn if a server uses both a config directory and a config path.
This is a potentially breaking change: while …
> Ignore overlapping -config file/dir options passed to server

- go.mod
- go.sum
Note that runc is not embedded in our final binary and so this only impacted testing, not release builds.
Resolves: https://github.com/openbao/openbao/security/dependabot/3
> Update github.com/opencontainers/runc to v1.1.14

- go.mod
- go.sum
We're already using `gofumpt@latest` in our `Makefile` so this doesn't affect formatting.
> Update gofumpt tool dependency

- .github/workflows/release.yml
- .goreleaser-template.yaml
- Makefile
This creates release tooling for HSM binaries. 
---
To be merged after #943.
> Add PKCS#11 auto-unseal builds to release workflow

- scripts/docker/docker-entrypoint.sh
Allow the config directory env var to be overridable so that it will work inside of bankvaults deployments.
> Set BAO_CONFIG_DIR to a default but let it be overridable.

- builtin/logical/kv/backend.go
- builtin/logical/kv/path_metadata.go
- builtin/logical/kv/path_metadata_test.go
- changelog/766.txt
- website/content/api-docs/secret/kv/kv-v2.mdx
Allow KV to list detailed information about metadata keys. With paginated listing and transactional storage, this allows a single, consistent view of metadata (including `current_version`, which in turn gives a consistent view over all data). This incurs additional work (reading each entry) and thus is done under a new path to allow separate ACLing.
---
This will be rebased once #763 lands, as it conflicts and also to take advantage of the new SCAN operation to support recursively listing all keys in K/V.
> Add detailed metadata list to KV

- CHANGELOG.md
- changelog/811.txt
- go.mod
- website/content/docs/release-notes/2-2-0.mdx
- website/sidebars.ts
Adds the release note and changelog entry for v2.2.0-beta. Also updates the `sdk` module version, though this is strictly unnecessary since we use local replacements during build.
> Release v2.2.0 beta20250213

- changelog/1013.txt
- vault/identity_store_util.go
When listing the `identity/entity-alias/id` endpoint it can be helpful to also get the `metadata`, not only `custom_metadata`, which can be set by auth methods (OIDC provider for example).
This helps especially when you need to search for a specific user using the metadata on an entity-alias, as the alias-id should be a unique identifier (sub), that might not be an email address etc.
```
$ bao list -detailed identity/entity-alias/id
Keys                                    canonical_id                            custom_metadata         local    metadata                 mount_accessor            mount_path        mount_type    name
----                                    ------------                            ---------------         -----    --------                 -------------- …
```
> feat(identity/entity-alias): return metadata when listing entity-aliases

- command/commands.go
- command/operator_raft_demote.go
- command/operator_raft_promote.go
- physical/raft/raft.go
- physical/raft/raft_autopilot_promoter.go
- vault/external_tests/raft/raft_autopilot_test.go
- vault/logical_system_raft.go
- website/content/api-docs/system/storage/raft.mdx
- website/content/docs/commands/operator/raft.mdx
This is a follow up of #741 to allow managing the voter state of a node in the
cluster at runtime.  We provide new CLI commands `bao operator raft promote` and
`demote` to promote a non-voter to a voter and vice versa.  Matching API
endpoints at `sys/storage/raft/promte` and `demote` are also added for
convenience.
I am no sure yet if I should also expose this directly in the UI's Raft Storage
overview.
> Add API and CLI commands to promote/demote nodes in the Raft cluster

- .goreleaser-template.yaml
Turns out `.Prerelease` is not a boolean, so `skip_push` is never set to
false on a pre release. To fix this, we evaluate the environment
variable `GITHUB_RELEASE_PRERELEASE` instead.
Closes: #1004
> Fix prerelease image tagging

- http/util.go
- vault/namespaces_store.go
- vault/request_handling.go
During [live-coding with Andrii](https://youtu.be/Gm15qRTtiUY), we worked through correctly handling request routing with namespaces from paths or headers. Right now there is no support for child namespaces, but we've solved the issue with using the root namespace and the data race from the concurrent modification issue in http/util.go.
This doesn't yet allow secret engine mounting within a namespace; we still need to enable the `sys/`, `cubbyhole/`, and `identity/` mounts within the namespace's mount table and load them at runtime.
---
cc: @genelet @driif @klaus-sap @phyrog @voigt @satoqz
> Correctly handle request routing

- website/content/api-docs/secret/pki.mdx
The link to **create/update role** is broken in the PKI Table of Contents. 
To fix this, we can either update the href to `#createupdate-role`, as observed in the raw HTML, or explicitly specify a heading ID, as I have done, following the [docusaurus docs](https://docusaurus.io/docs/markdown-features/toc#heading-ids).
> Nit: Fix link to create/update role in api/pki docs

- command/commands.go
- command/operator_raft_demote.go
- command/operator_raft_promote.go
- physical/raft/raft.go
- physical/raft/raft_autopilot_promoter.go
- vault/external_tests/raft/raft_autopilot_test.go
- vault/logical_system_raft.go
- website/content/api-docs/system/storage/raft.mdx
- website/content/docs/commands/operator/raft.mdx
* add commands to promote and demote raft peers
Building on top of the new non-voter feature, this allows controlling
the voting status of individual nodes using the CLI.
* document new commands and api endpoints
* remove DR Token options
This is not supported by OpenBao and probably never will be.
* add fallback if autopilot is disabled
Use the raw Raft backend functions to promote or demote a node.
---------
-------
> Backport: Add API and CLI commands to promote/demote nodes in the Raft cluster (#996)

- .github/dependabot.yml
Attempt to fix Dependabot not opening PRs for workflow files in `.github/actions/*` by adding a wildcard to the directory path.
References:
* [Dependabot directory options](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#directories-or-directory--)
* [Defining multiple locations for manifest files](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files)
> Add wildcard so Dependabot traverses child directories

- vault/barrier.go
- vault/barrier_aes_gcm.go
Several commits earlier renamed master->root key in the hierarchy but never did a migration. This does not perform an active migration but instead defers it to new initialization or root key rotation.
---
This makes reconciling storage with code more difficult as the only place still calling it the `master key` was in storage and all the code refers to it as the root key.
> Use consistent path for root key

- vault/auth.go
- vault/auth_test.go
- vault/core.go
- vault/mount.go
- vault/mount_test.go
- vault/namespaces_store.go
When setting up namespaces, we're required to create additional mounts
for sys/, identity/, cubbyhole/, and token/ within the namespace. Of
these, cubbyhole is never persisted but is instead a dynamic mount,
whereas the remainder exist in the underlying storage.
We don't yet handle the separation of these mounts' data by namespace;
this will be handled in later updates to this branch. Many singleton
stores like TokenStore and PolicyStore will need broader updates to
align with the RFC's data storage model.
This was created during live-coding with @satoqz.
`Signed-off-by: Alexander Scheel <ascheel@gitlab.com>`
----
Resolves: #1029
cc: @genelet @driif @klaus-sap @phyrog @voigt @satoqz
> Create required mounts when setting up namespace

- website/content/docs/rfcs/index.mdx
This PR adds the [RFC#432](https://github.com/openbao/openbao/issues/432) to the RFC-Index of the [documentation on the OpenBao Website](https://openbao.org/docs/rfcs/).
> docs: add rfc#432 to docs rfc index

- vault/audit.go
- vault/auth.go
- vault/core.go
- vault/mount.go
- vault/mount_test.go
- vault/mount_util.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
Resolves #1067
- Implements Cubbyhole (storage-wise) awareness of namespace by refactoring 
`(*mountEntry).View()` into `(*Core).mountEntryView()`
- Adjusts the logical backend creation of `CubbyholeNS` to reuse the existing root owned Cubbyhole backend
___
cc: @cipherboy @klaus-sap @satoqz @phyrog @voigt @driif
> Implement namespace aware Cubbyhole #1067

- website/content/docs/configuration/listener/tcp.mdx
The documentation had a confusing duplication of `tls_acme_ca_directory`. From looking at the defaults & the code of `certmagic`, it looks like one of them should be `tls_acme_test_ca_directory` instead.
Resolves #1121
Also add a note about the `tls_acme_cache_path` - if I undestand correctly, this is the `Storage` passed to the `certmagic` instance, and needs to be shared across cluster members if issuing certificates for a cluster behind a load-balancer or otherwise using a shared hostname. I was confused about how this might work when reading about the feature. Happy to remove this change though, since it's not directly related to the issue.
> Fix ACME TLS documentation

- website/content/docs/configuration/seal/pkcs11.mdx
OpenBao requires the key to be generated externally inside the HSM. This PR removes phrases suggesting OpenBao can generate the key by itself.
> fix(docs/pkcs11): remove documentation regarding key generation

- website/content/docs/policies/osps-baseline.mdx
This pull request adds a page to the docs on the project website, that covers the [OSPS ](https://baseline.openssf.org/)baseline by OpenSSF. The page contains a table, that has the level 1 controls and can be used to track implementation progress.
This is sort of a blind shot, so do not be afraid to propose changes or a different solution. I could not find any examples about best practices for the implementation of the baseline, as it is quite new. 
Closes #1109
> Add webpage for OSPS baseline

- sdk/helper/template/funcs.go
- sdk/helper/template/funcs_test.go
- sdk/helper/template/template.go
- sdk/helper/template/template_test.go
Per PolicyStore.sanitizeName, ACL policies must have lower case names, not reflected in documentation. This makes the original choice of base64 (in #618) not work well: base64 is case sensitive and thus does not survive lowercase conversion.
Using hex allows us to retain the original purpose but without making the policy store case-sensitive (as that would likely be a breaking change).
> Add hex to templating for ACL policies

- builtin/logical/pki/backend_test.go
- changelog/1139.txt
`logical/pki/backend_test.go` is sporadically failing in the `race` tests. This change allows a few retries of the assertions in question, as there appears to be a timing issue.
Resolves #1097
> PKI test failure

- vault/policy_test.go
- website/content/docs/concepts/policies.mdx
Uncommenting the JSON test fails presently:
--- FAIL: TestPolicy_Parse (0.00s)
--- FAIL: TestPolicy_Parse/JSON (0.00s)
policy_test.go:247: value: &vault.PathRules{Path:"test/types", Policy:"", Permissions:(*vault.ACLPermissions)(0xc000467570), IsPrefix:false, HasSegmentWildcards:false, Capabilities:[]string{"create", "sudo"}, MinWrappingTTLHCL:interface {}(nil), MaxWrappingTTLHCL:interface {}(nil), AllowedParametersHCL:map[string][]interface {}{"int":[]interface {}{1, 2}, "map":[]interface {}{map[string]interface {}{"good":"one"}}}, DeniedParametersHCL:map[string][]interface {}{"bool":[]interface {}{}, "string":[]interface {}{"test"}}, RequiredParametersHCL:[]string(nil), MFAMethodsHCL:[]string(nil), PaginationLimitHCL:0}
policy_test.go:494: …
> Validate policies can contain comments, be JSON

- website/content/docs/rfcs/index.mdx
- website/content/docs/rfcs/ssh-ca-multi-issuer.mdx
- website/sidebars.ts
Following the work done on #880, this PR adds the RFC, #679, to the website's RFCs.
Resolves #679
> docs: Add SSH CA Multi-issuer RFC to website docs

- command/commands.go
- command/namespace.go
- command/namespace_scan.go
- command/namespace_scan_test.go
This PR adds `bao namespace scan` subcommand.
This command recursively lists all (child) namespaces and is namespace aware.
This resolves #1063
```
$ bao namespace scan
Keys
----
reply/
reply/comsysto/
reply/ki/
reply/ki/christoph/
reply/liquid/
$ bao namespace scan -ns=reply
Keys
----
comsysto/
ki/
ki/christoph/
liquid/
```
> feat: add `bao namespace scan`

- helper/namespace/namespace.go
- helper/namespace/namespace_test.go
- vault/logical_system_namespaces_test.go
Resolves #1023 with some changes introduced already with #1051
From the issue:
> Expected Behavior:
> The error message should:
> Clearly indicate that certain characters are not allowed
- done for empty spaces
> Specify which characters are prohibited
- as above, only empty spaces are forbidden, as "/" are handled at the request level
> Provide guidance on valid namespace naming conventions
- I don't think it's necessary that we give any hints as for the name convention, as there are almost none restrictions, the only two (with appropriate error messages) are: reserved name and empty space
**This PR**:
- Fixes the bug that enabled namespace creation with the reserved name (`sys`, `cubbyhole`)
**Q: "should we also restrict naming the namespace as `namespace`"?**
```
bao namespace create …
```
> Implement namespace name restrictions #1023

- .github/workflows/mirror.yml
We decided it might be a good idea to provide an official repository mirror other than GitHub. This adds an action to mirror the main branch to Codeberg.
> Add action to mirror repo to Codeberg

- website/content/docs/plugins/plugin-authors-guide.mdx
Lists benefits of implementing `/detailed` endpoint vs using `- detailed` flag.
> Add guide for listing detailed endpoints

- ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js
`test-ui` is failing and this is the log: 
```
not ok 1 Chrome 135.0 - [1250 ms] - Acceptance | settings/configure/secrets/ssh: it configures ssh ca
---
actual: >
SSH Certificate Authority Configuration saved!
expected: >
missing public_key
stack: >
at Object.<anonymous> (http://localhost:7357/ui/assets/tests.js:6411:14)
message: >
renders warning flash message for failed save
...
```
The SSH secrets engine no longer requires a mount‑level public_key after #880: 
```
fatima@fattiesPatties-2 openbao % bao secrets enable -path=ssh-test ssh 
Success! Enabled the ssh secrets engine at: ssh-test/
fatima@fattiesPatties-2 openbao % curl -s -o /dev/null -w "%{http_code}\n" \
-H "X-Vault-Token: $BAO_TOKEN" \
-X
```
This updates the acceptance test to expect the success flash “SSH Certificate …
> Fix test-ui failing test

- .release/linux/package/usr/lib/systemd/system/openbao.service
- changelog/1179.txt
This is not needed anymore since https://github.com/golang/go/issues/46279 was resolved.   golang automatically raises the soft limit on startup.
Quoting https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Process%20Properties
> **Don't use.** Be careful when raising the soft limit above 1024, since select(2) cannot function with file descriptors above 1023 on Linux. Nowadays, the hard limit defaults to 524288, a very high value compared to historical defaults. Typically applications should increase their soft limit to the hard limit on their own, if they are OK with working with file descriptors above 1023, i.e. do not use select(2). Note that file descriptors are nowadays accounted like any other form of memory, thus there should not be any need to lower the hard …
> Do not set LimitNOFILE

- website/content/docs/configuration/telemetry.mdx
Add `metrics_prefix` configuration details in `telemetry` stanza documentation
Relatets to #1145
> doc(telemetry.mdx): add metrics_prefix

- http/handler.go
- http/handler_test.go
- http/util.go
Resolves #1070  
_Questions from the issue:_
> Should sys/quotas/rate-limit be restricted in the first place?
Depends on the implementation of quotas we want to do within OpenBao (not this PR)
> We have sys/quotas/lease-count in the restricted APIs - I don't think those exist in OpenBao?
Definitely a leftover from [upstream](https://developer.hashicorp.com/vault/api-docs/system/lease-count-quotas) implementation 
> Has this broken any other APIs besides sys/raw?
To be honest it hasn't broken the listing of the `sys/raw/sys` resources, as `bao list sys/quotas/rate-limit` is the equivalent of `bao list sys/raw/sys/quotas/rate-limit` and that worked as always. But to answer the question, yes this broke the usage of `bao list sys/raw/sys...` for restricted APIs
**Before**:
```
bao list …
```
> Namespaces Regression: Restricted APIs in `sys/raw`

- helper/namespace/namespace.go
- http/sys_namespaces_test.go
- vault/logical_system_namespaces.go
- vault/namespaces_store.go
This adds a fuzz test for the namespaces API to check for characters that cause problems. It also adds checks to the `(*Namespace).Validate` function for the characters found so far. All illegal characters now return a `400` error code, except for:
- `.`, and `..` return `405` and `404` respectively. They are interpreted by the HTTP stack, so these never reach the actual namespace validation. Not much that we can do here, I'm afraid.
Resolves #1183 
cc: @cipherboy @driif @klaus-sap @satoqz @voigt @wslabosz-reply @genelet
> Forbid illegal namespace characters

- helper/namespace/namespace.go
- vault/audit.go
- vault/auth.go
- vault/counters.go
- vault/expiration.go
- vault/expiration_test.go
- vault/identity_store_test.go
- vault/logical_system.go
- vault/logical_system_namespaces.go
- vault/mount.go
- vault/mount_test.go
- vault/namespaces_oss.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
- vault/namespaces_store_tree.go
- vault/policy_store.go
- vault/policy_store_test.go
- vault/testing.go
- vault/token_store.go
- vault/token_store_test.go
Resolves #1166.
- Moves UUID field from `NamespaceEntry` into `Namespace`
- Removes unnecessary fetches from NamespaceStore
- Use `(*Core).ListNamespaces` and `(*Core).NamespaceByID` where now possible
- Removes `NamespaceEntry` completely
cc: @cipherboy, @driif, @voigt, @wslabosz-reply
> move namespace uuid into namespace struct

- website/content/docs/configuration/seal/gcpckms.mdx
We recently stumbled across this internally when attempting to start OpenBao with GCP CloudKMS without explicitly setting region.
Thanks to Gonzalo Servat for identifying this.
> Clarify that region is required

- vault/diagnose/tls_verification_test.go
The Baltimore CyberTrust CA is expiring soon; it is a global root CA installed in most system trust stores but otherwise appears on our diagnose tests. Exclude this particular certificate's serial number from our test suite for now.
See also: https://tls-observatory.services.mozilla.com/static/certsplainer.html?id=16
---
As reported by @driif, thank you!
> Fix vault/diagnose test failure

- ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js
`test-ui` still fails after #1210 with a different error but the same ssh test:
```
not ok 2 Chrome 135.0 - [4621 ms] - Acceptance | settings/configure/secrets/ssh: it configures ssh ca
---
stack: >
Error: Element not found when calling `click('[data-test-ssh-input="generate-signing-key-checkbox"]')`.
at http://localhost:7357/ui/assets/test-support.js:46297:15
at async Object.<anonymous> (http://localhost:7357/ui/assets/tests.js:6412:7)
message: >
Promise rejected during "it configures ssh ca": Element not found when calling `click('[data-test-ssh-input="generate-signing-key-checkbox"]')`.
```
The reason is because even when the checkbox for **Generate signing key** (Specifies if OpenBao should generate the signing key pair internally) is left unticked and the key pair is not provided, it …
> Fix test-ui

- builtin/logical/ssh/path_config_ca_test.go
- builtin/logical/ssh/util.go
As discussed [here](https://github.com/openbao/openbao/pull/880#discussion_r2051177603), there is a bug in the issuer submission/generation endpoints where the parameter `generate_signing_key=false` was not being honored. This diff fixes it, returning a 400 response with the error message `missing public_key` and introduces a test for the parameters.
> fix(ssh): `generate_signing_key=false` not honored on issuer submission endpoints

- builtin/logical/pki/acme_errors.go
- changelog/1236.txt
While JSON arrays may be empty, RFC 8259 does not necessarily ensure that the literal value `null` is type-equivalent to an array. This means that sending `{"subproblems":null}` is not valid under RFC 8555. This breaks compatibility with some type-sensitive ACME clients.
See also: https://github.com/certbot/certbot/pull/10001
> Do not encode empty subproblems in ACME

- ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js
In #1210 and #1211, I updated the SSH configuration UI test to mirror the behavior of the SSH engine. However, that behavior was later identified as unintended and patched in #1235. This PR updates the test to reflect the intended behavior of the engine, ensuring consistency and helping clean up the pipeline! :D
> Match ssh test to updated behaviour

- builtin/logical/pki/acme_errors.go
- changelog/1236.txt
* Do not encode empty subproblems in ACME
While JSON arrays may be empty, RFC 8259 does not necessarily ensure that the literal value `null` is type-equivalent to an array. This means that sending `{"subproblems":null}` is not valid under RFC 8555. This breaks compatibility with some type-sensitive ACME clients.
See also: https://github.com/certbot/certbot/pull/10001
---------
Resolves #
> Do not encode empty subproblems in ACME (#1236)

- vault/diagnose/tls_verification_test.go
* Fix vault/diagnose test failure
The Baltimore CyberTrust CA is expiring soon; it is a global root CA installed in most system trust stores but otherwise appears on our diagnose tests. Exclude this particular certificate's serial number from our test suite for now.
* Update vault/diagnose/tls_verification_test.go
---------
Resolves #
> Fix vault/diagnose test failure (#1221)

- Makefile
After splitting the goreleaser template into separate files, we needed to update the Makefile so that release verification could proceed.
> Fix make goreleaser-check after split

- helper/namespace/namespace.go
- http/sys_namespaces_test.go
- vault/auth.go
- vault/expiration.go
- vault/expiration_test.go
- vault/logical_system.go
- vault/logical_system_namespaces.go
- vault/logical_system_namespaces_test.go
- vault/logical_system_test.go
- vault/mount.go
- vault/mount_test.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
- vault/namespaces_store_tree.go
- vault/policy_store.go
- vault/policy_store_test.go
- vault/router.go
Resolves #1025
implements the `delete namespace` operation with following assumptions:
- requests to core have a deadline of 90 seconds, and the deletion operation might take an unknown period of time, depending on the amount of resources to free up, we opt for asynchronous operation
- delete namespace now taints the namespace, blocking all future requests to the tainted namespace
- namespace taint is persisted, all other non-leader nodes will also reject the request
- delete namespace returns a response of `"status": "in-progress"`
- TODO:  for further enhancements, add the status endpoint for checking the deletion progress 
- TODO: in case of the interruption of the deletion operation, the operator should retry the delete operation resulting in a one more attempt at the deletion
```
bao …
```
> Implement Cascading Delete for Namespaces and Associated Resources

- vault/core.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
Within preSeal, we faced a race condition:
- NamespaceStore was first destroyed
- Then RollbackManager was stopped.
In particular, this ordering means that any rollback functions which
relied on namespaces, such as the token or identity subsystems, would
occasionally panic.
This was only reported in CI, but the code path is reachable in
production systems and thus may have manifested in heavy load scenarios.
Tear down the namespace store as the very last thing, so that rollback
manager and any dangling mount options can access namespaces if
necessary.
---
cc: @wslabosz-reply @klaus-sap @satoqz @phyrog @voigt @driif
> Fix preSeal ordering w.r.t NamespaceStore

- helper/namespace/namespace.go
- http/util.go
- vault/external_tests/quotas/quotas_test.go
- vault/logical_system_quotas.go
- vault/mount.go
- vault/mount_test.go
- vault/namespaces_oss.go
- vault/namespaces_store.go
- vault/quotas/quotas.go
- vault/quotas/quotas_rate_limit.go
- vault/quotas/quotas_rate_limit_test.go
- vault/quotas/quotas_test.go
This PR addresses #1084 and replicates namespace-aware quota behavior.
```bash
$ bao namespace create ns1
Key                Value
---                -----
custom_metadata    map[]
id                 g7B5Hn
path               ns1/
uuid               4f4afac3-adbf-baad-6576-6444a9e19a64
$ bao write sys/quotas/rate-limit/foo-limit path="ns1" rate=100 interval=2s
Success! Data written to: sys/quotas/rate-limit/foo-limit
$ bao read sys/quotas/rate-limit/foo-limit
Key               Value
---               -----
block_interval    0
inheritable       false
interval          2
name              foo-limit
path              ns1/
rate              100
role              n/a
type              rate-limit
```
The quota api endpoints under `/sys/quotas` remain restricted and can't be called in …
> Add namespace-aware rate-limit quota

- website/content/docs/commands/operator/rekey.mdx
The https://openbao.org/docs/commands/operator/rekey/ page has two minor issues:
* still references hashicorp as keybase key names
* one example has broken end-of-line handling in shell excerpt
> Minor cleanup of the rekey webpage

- vault/dynamic_system_view_test.go
- vault/mount.go
- vault/password_policy_util.go
Resolves #1263
In addition to checking the written storage paths, we did some testing with the database secrets engine + Postgres, ensuring that it can only find the password policies for the namespace the engine is enabled in.
> Namespace-aware password policy storage & lookup

- website/content/docs/policies/osps-baseline.mdx
> While active, the [project documentation](https://baseline.openssf.org/versions/2025-02-25#project-documentation) MUST include an explanation of the contribution process.
The project does include a [contribution guide](https://github.com/openbao/openbao/blob/main/CONTRIBUTING.md).
Resolves [dev-wg #17](https://github.com/openbao/dev-wg/issues/17)
> Affirm Level 1: OSPS-GV-03.01

- website/content/docs/policies/osps-baseline.mdx
> When the project has made a release, the project documentation MUST include user guides for all basic functionality.
Whenever changes are made to OpenBao's functionality, the pairing docs are also updated at https://openbao.org/docs/. Additionally [release notes](https://openbao.org/docs/release-notes/) are written for major updates in new versions of OpenBao.
Resolves [dev-wg #18](https://github.com/openbao/dev-wg/issues/18)
> Affirm Level 1: OSPS-DO-01.01

- vault/namespaces_store.go
- vault/quotas/quotas.go
- vault/quotas/quotas_test.go
Followup to #1161 and #1206 because it turns out "it depends" would have been the correct answer to https://github.com/openbao/openbao/pull/1161#discussion_r2068161550 😄
Quotas attached to a mount are automatically deleted on unmount, which ususally clears all namespace-specific quotas on namespace deletion.
There's one edge case where quota is not attached to the mount and thus not removed on namespace deletion yet:
`path=foo/bar` where `foo/bar` is a namespace, no mount path, no API path
---
cc @cipherboy @voigt @wslabosz-reply
> Delete namespace-level quota on namespace deletion

- changelog/1297.txt
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
- website/content/docs/configuration/storage/postgresql.mdx
When using the PostgreSQL storage implementation, libpgx supports component-wise standard environment variables for connection information. This means that one complete connection string may not be present but the connection would still succeed. Support empty connection information as a result.
> Allow empty PostgreSQL connection URLs

- api/client.go
- command/base.go
- command/base_flags.go
- command/base_flags_test.go
Fixes two integer conversion issues on 32 bit systems. Both are unlikely to occur in real life (both are config related and only occur on numbers > MaxInt if MaxInt < MaxInt64), but better safe than sorry.
> Fix incorrect conversion between integer types (on <64 bit systems)

- api/logical.go
- api/request.go
- changelog/1315.txt
Caused by discussion on https://github.com/openbao/openbao/pull/1300#discussion_r2084843533
whenever there's explicit `nil` data provided to either `WriteWithContext` or `JSONMergePatch`, `(*request).setJSONBody` would marshal and set the marshaled data as a request body. This introduces a bug in a `output-curl-string` flag usage, as it creates invalid requests with a body of `-d 'null'`
Check for `nil` data in `SetJSONBody` method and return immediately from function if it's encountered.
In the PR also included removal of unused function parameter `path` in `(*Logical).write` method.
> Fix marshaling and setting nil request body

- vault/auth.go
- vault/expiration.go
- vault/logical_system_namespaces.go
- vault/namespaces_store.go
- vault/namespaces_store_test.go
- vault/token_store.go
[namespace deletion: avoid outdated reads](https://github.com/openbao/openbao/pull/1311/commits/3b8663123f3ab88aa5b930cdfbefcc3eec453299) fixes an edge case where tests reached
https://github.com/openbao/openbao/blob/7e053be408876c51c35d54d1763f02828b50e8c1/vault/logical_system_namespaces.go#L353
on my machine :-)
[expiration manager: fix deadlock on seal](https://github.com/openbao/openbao/pull/1311/commits/f370e97c1973010c774fc2d809a250594ed73127) fixes https://github.com/openbao/openbao/actions/runs/14926238096/job/41931694374
[token store: wait for tidy before teardown](https://github.com/openbao/openbao/pull/1311/commits/047f2786ac59098390d0e3b1109d84a66475830b) fixes https://github.com/openbao/openbao/actions/runs/14969013713/job/42045556523
> Namespaces: Test flake, deadlock, race condition cleanup

- builtin/credential/jwt/path_config.go
- builtin/credential/jwt/path_config_test.go
- changelog/1306.txt
- website/content/api-docs/auth/jwt.mdx
When OpenBao is brought up alongside other infrastructure, the OIDC discovery URL may not be valid yet. Rather than delaying OpenBao configuration until OIDC is available, add a lazy validation parameter, `skip_jwks_validation`, to allow OIDC and JWKS URLs to be lazily validated.
Reading the auth config (`/auth/jwt/config`) will now report status of the issuer.
---
@DrDaveD This needs docs &c, but this is roughly what I was thinking. Let me know your thoughts. :-)
> Allow lazy discovery of OIDC connection information

- changelog/1280.txt
- helper/testhelpers/postgresql/postgresqlhelper.go
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
- website/content/docs/configuration/storage/postgresql.mdx
When starting OpenBao, we formerly assumed that the database instance was already up and running. In certain scenarios, such as executing in the context of Kubernetes, with a PGBouncer instance, or in Podman Compose, we might have a looser coupling of service availability. Support graceful retry logic in the initial connection handler to accommodate startup ordering issues.
> Support retrying PostgreSQL connection

- vault/barrier_aes_gcm.go
- vault/barrier_aes_gcm_test.go
As reported by @LuyeT, migration of the root key entry causes a
deadlock. This is because, while holding the write lock, we attempt to
call `barrier.Get(...)`, which acquires its own read lock. Use the
lockless variant instead to avoid this.
Resolves: #1111
---
Many thanks to @DanGhita for identifying the cause of the bug.
This can be tested with the attached test case, or by upgrading from v2.2.0 to v2.3.0 (with e.g., Raft) prior to this change.
> Fix deadlock on legacy root key path migration

- changelog/1299.txt
- physical/postgresql/postgresql.go
- physical/postgresql/postgresql_test.go
Calling `db.SetMaxOpenConns(...)` has the same effect as using a permit
pool; Go will internally do locking and ensure that no more connections
are created.
Adds a test case to verify this behavior, which should allow us to avoid
double locking and the latency that brings with.
---
This is based on #1280 and will be rebased when it lands.
> PostgreSQL - Remove redundant PermitPool

- changelog/1323.txt
- sdk/framework/field_data.go
- sdk/framework/field_data_test.go
When sending an API request with incorrect typing of request data, OpenBao (and HashiCorp Vault) would leak information in service and audit logs. The original disclosure from HashiCorp states this is limited to KVv2, but this is applicable to any secrets engine.
See also: https://discuss.hashicorp.com/t/hcsec-2025-09-vault-may-expose-sensitive-information-in-error-logs-when-processing-malformed-data-with-the-kv-v2-plugin/74717
> Prevent information disclosure on invalid request

- website/content/docs/configuration/index.mdx
This also makes it the default example; as far as examples go, I think this makes more sense than HCL tbh.
> Add JSON configuration example to website

- changelog/1349.txt
See https://github.com/openbao/go-kms-wrapping/pull/32#pullrequestreview-2864263148.
> Release note on PKCS#11 library finalization (see go-kms-wrapping)

- changelog/1346.txt
- command/operator_diagnose.go
- command/server.go
- internalshared/configutil/pkcs11.go
Seal configuration collects "info keys" from e.g. KMS configuration but fails to ultimately display these in log output because Go slices are complicated.
With this fix, the configuration is printed as intended:
```
==> OpenBao server configuration:
PKCS#11 KMS Key Label: bao-root-key-aes
PKCS#11 KMS Library: /opt/homebrew/lib/softhsm/libsofthsm2.so
PKCS#11 KMS Token Label: OpenBao
Administrative Namespace:
Api Address: http://127.0.0.1:8200
Cgo: enabled
Cluster Address: https://127.0.0.1:8201
```
I'm a bit unhappy with how all the "PKCS#11 KMS" prefixes align here (same issue for different KMS types) but not sure what to do about it 😄
> Display seal configuration info keys in logs

- changelog/1224.txt
- vault/logical_system.go
- vault/logical_system_paths.go
- vault/logical_system_test.go
This PR allows Openbao to list detailed information about capabilities in policies endpoint, avoiding N+1 while trying to retrieve the policies and their capabilities.
Issue link: https://github.com/openbao/openbao/issues/1156
> Detailed metadata in policy endpoint

- changelog/1348.txt
- vault/core.go
- vault/core_metrics.go
- vault/core_test.go
- vault/core_util.go
- vault/counters.go
- vault/logical_system.go
- vault/logical_system_user_lockout.go
- vault/login_mfa.go
- vault/namespaces_store.go
- vault/request_handling.go
- vault/token_store.go
Resolves comment raised here https://github.com/openbao/openbao/pull/1165#discussion_r2082603412
- Removes `barrierViewForNamespace` and `collectNamespaces` from `core_util.go`, replacing it's usage with `NamespaceView` and `List(All)Namespaces` respectively
- Adjusts `LockedUsers` feature storage location, moving it from root's `core/login/locked-users/<ns-id>/<mount-accessor>/<aliasName>` to `(namespaces/<ns_uuid>)/core/login/locked-users/<mount-accessor>/<aliasName>`
- Adjusts the storage considerations of MFA configs and MFA login-enforcements and TOTP keys
- Moves the `teardownLoginMFA()` before `teardownNamespaceStore()` in `PreSeal()`
- Simplifies `getLockedUsersResponses` as with namespace deletion the storage containing locked users entries also gets deleted we no longer have to …
> MFA Login namespace adjustments

- website/src/pages/downloads.tsx
So far https://openbao.org/downloads/ did not reference OpenBaos HSM docker distribution. This PR adds docker pull instructions for HSM.
> add hsm docker distribution to downloads page

- CHANGELOG.md
SECURITY:
* sdk/framework: prevent information disclosure on invalid request. HCSEC-2025-09 / CVE-2025-4166. [[GH-1323](https://github.com/openbao/openbao/pull/1323)]
BUG FIXES:
* ui: Fix description of Organizational Unit (OU) field in PKI. [[GH-1333](https://github.com/openbao/openbao/pull/1333)]
> Release 2.2.2

- CODEOWNERS
After the creation of the new teams, we should add them to the CODEOWNERS file.
> Add new core, kubernetes teams to CODEOWNERS

- builtin/logical/kv/path_metadata.go
- builtin/logical/kv/path_metadata_test.go
- changelog/1388.txt
Unlike scan, list results include directories in their results. This results in KVv2 panicing when attempting to fetch metadata about the entry, as it doesn't exist and thus returns nil. We should handle this gracefully.
> Fix detailed metadata on list results

- .github/dependabot.yml
See the recent surge of Docusaurus updates: https://github.com/openbao/openbao/pull/1421, https://github.com/openbao/openbao/pull/1420, https://github.com/openbao/openbao/pull/1419, https://github.com/openbao/openbao/pull/1418, https://github.com/openbao/openbao/pull/1417
From https://github.com/openbao/openbao/actions/runs/15523975718/job/43700894961?pr=1421:
```
All official @docusaurus/* packages should have the exact same version as @docusaurus/core (number=3.8.0).
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```
This should group them into a single PR next time.
> Dependabot: Group `@docusaurus/*` updates

- changelog/1424.txt
- vault/core.go
- vault/seal.go
- vault/seal_autoseal.go
During beta version of upstream (v0.11.4) there was a deprecation of a `recovery-seal-config` entry path of recovery config. This PR removes the fallback checking old location for a possible migration to a new path.
This removal doesn't contradict the [OpenBao compatibility proposal](https://openbao.org/docs/policies/migration/#proposal). OpenBao supports migration from Vault v1.14, not guaranteeing the proper migration path from older versions (especially beta versions of Vault). This change removes complexity from the already complex system of sealing and seal migrations.
---
cc: @cipherboy
> Remove deprecated recovery config location fallback

- .github/workflows/release.yml
- Dockerfile
- goreleaser.hsm.yaml
See https://github.com/openbao/openbao/issues/1407#issuecomment-2952858958, we install cross-compiling GCC from the Ubuntu repositories and build a single `aarch64-unknown-linux-gnu` binary, then reuse it in Alpine images via `gcompat`.
We could easily add support for other architectures with the same pattern if there is interest.
Resolves https://github.com/openbao/openbao/issues/1407
> HSM: Add arm64 builds & Alpine containers

- go.mod
- go.sum
See `govulncheck`:
```
Vulnerability #1: GO-2025-3754
CIRCL-Fourq: Missing and wrong validation can lead to incorrect results in
github.com/cloudflare/circl
More info: https://pkg.go.dev/vuln/GO-2025-3754
Module: github.com/cloudflare/circl
Found in: github.com/cloudflare/circl@v1.3.7
Fixed in: github.com/cloudflare/circl@v1.6.1
```
Our outdated `github.com/ProtonMail/go-crypto v1.1.3` pulls in `github.com/cloudflare/circl v1.3.7`
Up to date `github.com/ProtonMail/go-crypto v1.3.0` pulls in `github.com/cloudflare/circl v1.6.0`, still vulnerable, so we manually bump to `v1.6.1`.
Not sure why Dependabot hasn't suggested the `github.com/ProtonMail/go-crypto` bump, ever?
> Bump ProtonMail/go-crypto and cloudflare/circl

- CODEOWNERS
Anyone should be able to approve changelog/ entries, and core should also own our go.{mod,sum} and .go-version files.
> Adjust go.*, changelog codeowners

- changelog/1438.txt
- command/server.go
- command/server/config.go
- command/server/config_test.go
Refactors the dev certificates. Additionally I saw that `-dev-tls-san` is not implemented yet.
This is required for the current implementation of the `openbao-k8s` integration tests.
For now I will remove the `-dev-tls-san` from the integration tests.
> chore(tls): refactor dev certificates to openbao

- changelog/1432.txt
- command/server.go
- command/server/config.go
- helper/namespace/namespace.go
- helper/storagepacker/storagepacker.go
- vault/core.go
- vault/identity_store.go
- vault/identity_store_oidc_provider.go
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/testing.go
- vault/token_store.go
- vault/token_store_test.go
This PR does three things:
1. Fix a bug wherein identities weren't being loaded for non-root namespaces.
2. Attach namespace accessors to automatically generated identifiers in the identity subsystem, similar to tokens. This will provide the basis for any safe group inclusion logic in the future.
3. Add an unsafe, default off, config flag for the identity system to behave like Vault Enterprise and allow weak multi-tenancy in the identity system. All that is needed to do to enable this is to use only a single MemDB instance, rather than attempting to look up entities across MemDBs. 
Resolves: #1110
> Fix identity store resolution

- website/content/docs/policies/osps-baseline.mdx
> While active, the license for the source code MUST be maintained in the corresponding repository's LICENSE file, COPYING file, or LICENSE/ directory.
The OpenBao license is stored in the repository's [LICENSE file](https://github.com/openbao/openbao/blob/main/LICENSE).
Resolves [dev-wg #18](https://github.com/openbao/dev-wg/issues/31)
> Affirm Level 1: OSPS-LE-03.01

- website/content/blog/2025-05-30-namespaces-announcement.md
- website/content/blog/2025-06-17-openbao-to-openssf.md
- website/content/blog/authors.yml
See also: https://openssf.org/blog/2025/06/17/openbao-joins-the-openssf-to-advance-secure-secrets-management-in-open-source/
> Add OpenBao to OpenSSF blog post

- .github/workflows/test-go.yml
Implemented fix in the `test-collect-reports` step. It retrieves the expected matrix IDs from the `test-matrix` job output and validates each matrix job individually by checking for the presence of `results-{id}.*` files. If any expected Go test matrix job results are missing, the job fails.
Resolves #1065
> fix(test-go): Verify test results before passing

- builtin/logical/pki/path_cel_test.go
This PR updates the CEL patch test. 
Previously, patching a single rule required: 
```
patchData := map[string]any{
"cel_program": map[string]any{
"variables": []map[string]any{
{
"name":       "require_ip_sans",
"expression": "size(request.ip_sans) >= 2", // new rule
},
},
},
}
```
After moving to `go-viper/mapstructure`, the whole variable list needs to be sent over: 
```
patchData := map[string]any{
"cel_program": map[string]any{
"variables": []map[string]any{
{
"name":       "require_ip_sans",
"expression": "size(request.ip_sans) >= 2", // new rule
},
{
"name":       "success",
"expression": "request.common_name == 'example.com' && require_ip_sans",
},
{
"name": "cert",
"expression": `CertTemplate{
Subject: PKIX.Name{
CommonName: request.common_name,
Country:    ["ZW", "US"],
}, …
```
> Update CEL patch test to ensure compatibility when moving to `go-viper/mapstructure`

- changelog/1478.txt
- physical/postgresql/postgresql.go
When using a PostgreSQL replica, creating the tables will fail with a `SQLSTATE 25006` error. Check our first table creation and ensure we're not trying to write to a replica; if we are, skip it.
This also fixes table creation to properly use the given transaction.
> Fix PostgreSQL table creation on replica

- changelog/1432.txt
- command/server.go
- command/server/config.go
- helper/namespace/namespace.go
- helper/storagepacker/storagepacker.go
- vault/core.go
- vault/identity_store.go
- vault/identity_store_oidc_provider.go
- vault/identity_store_test.go
- vault/identity_store_util.go
- vault/testing.go
- vault/token_store.go
- vault/token_store_test.go
* Attach namespace to identity information
When allowing cross-namespace identity store operations, we need to attach namespace information to avoid expensive searches across all child namespaces to find the correct namespace for a given identifier.
This change is not backwards compatible with previous versions; we will fail sanitization for any existing entities in namespaces due to the lack of the namespace identifier suffix.
* Make StoragePacker transaction-friendly
The current StoragePacker design retains a copy of logical.Storage, avoiding the need for callers to use their own. However, it doesn't actually use the View interface, meaning we can apply transactions over the top for sensitive operations.
Expose storage as a parameter so that we can have cross-operation transactions.
* …
> Fix identity store resolution (#1432)

- Makefile
- builtin/logical/pki/cert_template.pb.go
- builtin/logical/pki/cert_template.proto
- builtin/logical/pki/path_issue_sign.go
- builtin/logical/pki/path_issue_sign_test.go
- builtin/logical/pki/translate_cert.go
- sdk/helper/cel/helpers.go
- sdk/helper/certutil/helpers.go
- sdk/helper/certutil/types.go
I was testing this with the following CEL program:
<details>
<summary>Program</summary>
```cel
{
"cel_program": {
"variables": [
{
"name": "have_cn",
"expression": "'common_name' in request && size(request['common_name']) > 0"
},
{
"name": "valid_cn",
"expression": "have_cn && request['common_name'].endsWith('.local.cipherboy.com')"
},
{
"name": "valid",
"expression": "valid_cn"
},
{
"name": "cn_value",
"expression": "have_cn ? request['common_name'] : ''"
},
{
"name": "subject",
"expression": "have_cn ? PKIX.Name{CommonName: cn_value} : null"
},
{
"name": "dns_sans",
"expression": "have_cn ? [cn_value] : null"
},
{
"name": "extensions",
"expression": "[PKIX.Extension{Id: [1, 2, 3, 4, 5], Critical: true, Value: b'issued by OpenBao'}]"
},
{
"name": "cert",
"expression": …
```
> Minor improvements to CEL for PKI 

- command/server.go
- command/server/config.go
- command/server/config_test.go
- command/server/config_test_helpers.go
- command/server/config_test_helpers_util.go
- vault/core.go
Load (and reload) `external_keys` stanzas. I think keeping these in `Core.rawConfig` with easy map lookup by name might be enough.
Also removed some enterprise hooks that crossed my path.
> External Keys: Parse configuration stanzas

- changelog/1527.txt
- command/server.go
When running in development mode using the Windows version of the binary, there is a typo in the command used to set the "BAO_ADDR" environment variable. This PR aims to correct this typo so that the command works correctly.
As described in the documentation, I did not create an issue for this PR, as it is just a minor typo.
> Fix typo in dev mode

- website/content/docs/platform/k8s/index.mdx
Since Vault Secret operator is currently not working and so, not included in documentation, the documentation should only count the 2 working and documented integrations. This avoid users looking for the missing third integration.
> doc: fix the number of kubernetes integration

- changelog/1539.txt
- vault/identity_store_oidc_provider.go
- vault/identity_store_oidc_provider_test.go
- vault/identity_store_oidc_provider_util.go
Fixes: #1536
- Looked around for more suitable alternatives to `strings.Cut`, found `namespace.SplitIDFromString` but that function appears to have a lot more moving parts. But maybe it's more correct?
> fix(oidc-provider): correctly lowercase identity IDs

- vault/namespace_store.go
Pretty sure we're missing a read lock here, even though it hasn't shown up in any tests yet.
`checkInvalidation(...)` is not required as `GetNamespace*(...)` already calls it.
It would be nice to eventually get a refactor of the namespace store in to make our Mutex handling less messy and more efficient.
cc: @wslabosz-reply
> Namespace Store: Reuse locks across calls & fix missing locks

- vault/core_cache_invalidate.go
- vault/core_cache_invalidate_test.go
- vault/policy_store.go
Implement cache invalidation for namespaces and policies.
Required as a prerequisite for enabling standby nodes to handle read requests.
See #1550
See #1528 
> Implement cache invalidation for namespaces and policies

- sdk/physical/cache.go
- sdk/physical/inmem/cache_test.go
- sdk/physical/physical.go
- vault/core_cache_invalidate.go
- vault/core_cache_invalidate_test.go
Implement cache invalidation for `physical.Cache` and call it from `core.Invalidate`
Required as a prerequisite for enabling standby nodes to handle read requests.
See #1550
See #1528 
> Implement cache invalidation for physical.Cache

- website/content/docs/platform/k8s/helm/run.mdx
When reading the documentation while setting up openbao I was confused that it suddenly told me the web ui was not exposed even though I was already able to access it.
Then I found out that this documentation is out of date :) So here is a small fix :)
> Update run.mdx: HELM now exposes the web ui

- vault/core_cache_invalidate.go
- vault/core_cache_invalidate_test.go
- vault/router.go
Implement cache invalidation for plugins (assuming plugins already properly implement the `InvalidateKey` method of the  `sdk/logical.Backend` interface).
Required as a prerequisite for enabling standby nodes to handle read requests.
See #1550
See #1528 
> Implement cache invalidation for plugins

- api/client.go
- api/logical.go
- vault/external_tests/api/secret_test.go
Keeping this on Logical() limits the consumption; uses like Sys() and KVv2() and other top-level clients cannot also use this without reimplementing it. By moving it to Client, it sits alongside SetToken(...) and thus should be more discoverable.
As this has not landed in a release, it shouldn't require a changelog entry.
---
cc: @fcbajao
> Move inline auth to Client from Logical

- changelog/1594.txt
- vault/core.go
- vault/mount.go
- vault/namespace_store.go
This can happen, if a mount deletion is requested in parallel.
Resolves https://github.com/openbao/openbao/issues/1543
> Ignore missing mount during namespace deletion

- changelog/1609.txt
- command/commands.go
- command/operator_diagnose.go
- command/operator_diagnose_test.go
- command/operator_validate_config.go
- command/operator_validate_config_test.go
- command/server/test-fixtures/diagnose_bad_syntax.hcl
- command/server/test-fixtures/diagnose_unknown_property.hcl
- website/content/docs/commands/operator/diagnose.mdx
- website/content/docs/commands/operator/validate-config.mdx
- website/sidebars.ts
Resolves https://github.com/openbao/openbao/issues/1591
Useage:
```command
$ bao operator validate-config -config node-000.json
OpenBao v2.0.0-HEAD ('3918fbaa775aaaf228fbffdf4176960047a2a873+CHANGES'), built 2025-07-31T12:58:01Z
[ warning ] Validate Config: Unknown or unsupported field unknown found in configuration at node-000.json.
```
> Add bao operator subcommand for config validation

- changelog/1627.txt
- vault/identity_store_entities.go
- vault/identity_store_entities_test.go
- vault/identity_store_util.go
- vault/request_handling.go
When validating a policy is not the root policy, ensure we first lowercase policy names before comparing. This ensures a malicious entity administrator cannot directly escalate to the root policy. While this is nominally bad, any access to identity subsystem is highly privileged and should be adequately restricted as it allows granting access to additional policies. These policies may in turn allow writing new or modifying existing policies, which means practically root-like access anyways.
See also: https://discuss.hashicorp.com/t/hcsec-2025-13-vault-root-namespace-operator-may-elevate-token-privileges/76032
> Ensure lowercase policy in entities to forbid root policy

- builtin/logical/transit/path_keys_test.go
- changelog/1634.txt
- command/server/config.go
- command/server/config_test_helpers.go
- http/logical_test.go
- http/sys_audit_test.go
- http/sys_config_state_test.go
- http/sys_generate_root_test.go
- vault/core_test.go
- vault/logical_system.go
- vault/logical_system_test.go
- vault/testing.go
Audit mount creation via the API places too much control over the underlying host in the operator's hands, as [^1] has shown. This introduces two new server configuration options:
- `unsafe_allow_api_audit_creation (default: false)` controls the ability to create audit mounts via the API
- `allow_audit_log_prefixing (default: false)` controls the availability of the `prefix` audit mount option
In the future (v2.4) we plan to move audit mount management almost entirely into the configuration file, providing an alternative to the now deprecated management via API. For now, the creation of new audit mounts will require setting `unsafe_allow_api_audit_creation = true`. This option can be reloaded at runtime via SIGHUP. Existing audit mounts are unaffected, unless they use the `prefix` option, …
> Disable audit mount creation via API + disable audit log prefixing

- .github/workflows/release.yml
- LICENSE_DEPENDENCIES.tpl
This adds an `openbao-dist-<version>.tar.xz` release asset for use by packages that need to be built without access to the internet.  This will be used for example by Fedora/EPEL packaging and was [requested by a reviewer there](https://bugzilla.redhat.com/show_bug.cgi?id=2376217).
This doesn't make any changes to the openbao code so I don't think it needs a changelog entry.
I wasn't able to test a combination release of this along with the goreleaser assets because of some credentials missing from my repo, or something like that.  This creates a draft release so hopefully goreleaser will just complete that rather than complaining that it is already there.  I couldn't figure out how to make the release notes completely blank so this instead puts in a short placeholder to be overwritten by …
> Add release of distribution source tarball

- builtin/logical/totp/backend_test.go
- builtin/logical/totp/path_code.go
- changelog/1625.txt
- website/content/api-docs/secret/totp.mdx
Backport of https://github.com/openbao/openbao/pull/1625.
> Fix TOTP engine verification reuse bypass (#1625)

- builtin/credential/jwt/path_cel_login.go
- builtin/credential/jwt/path_cel_login_test.go
- builtin/credential/jwt/path_cel_role.go
- builtin/credential/ldap/backend_test.go
- builtin/credential/ldap/path_login.go
- builtin/credential/radius/path_login.go
- builtin/credential/userpass/path_login.go
- changelog/1632.txt
- vault/core.go
- vault/expiration_test.go
- vault/external_tests/userpass_binary/ip_token_binding_test.go
- vault/login_mfa.go
- vault/request_handling.go
```patch
commit 94657267e2730a00e83427b012a648fecbec4952
Author: Alexander Scheel <ascheel@gitlab.com>
Date:   Wed Aug 6 13:26:47 2025 -0500
Address login plugin lookahead contract failures
As part of HCSEC-2025-16, various plugins lacked did not conform to the
entity alias lookahead contract; a different alias was returned in the
login request as what is ultimately used at runtime. We have two ways of
solving this:
1. Only take the value at lookahead time. This means that for two users
X, Y with different input data but similar aliases (e.g., subtly
different LDAP bindings which result in accessing the same account),
lockout will be incorrect.
2. Or, we could strictly enforce that these two values match. This is
the approach we opt for and subsequently enforce through
authentication …
```
> Address login plugin lookahead contract failures

- .github/workflows/release.yml
This is to correct a [failure to upload](https://github.com/openbao/openbao/actions/runs/16821517603/job/47650673183) that happened during the 2.3.2 release.
> Always do git checkout in release-dist job

- builtin/audit/file/backend.go
#1651 was merged before I could mention this.
@satoqz  creating an all ones int and xor it with a mask is the same as the "bitwise complement" `^` unary operator (in go it even uses the same symbol as xor, most other languages use `~`)
Go even has a "bit clear" binary operator `&^`, a combination of "bitwise complement" (`^`) and "bitwise and" (`&`)
But I like your ASCII art :+1:
> use "bit clear" to simplify executable bit strip

- vault/audit.go
- vault/audit_broker.go
- vault/audit_test.go
- vault/core.go
- vault/core_cache_invalidate.go
- vault/core_cache_invalidate_test.go
- vault/mount.go
- vault/mount_test.go
Implement cache invalidation for audits
Required as a prerequisite for enabling standby nodes to handle read requests.
See #1550
See #1528 
This change is a bit more involved than the previous PRs for cache invalidation (e.g. #1551, #1584), because the storage key does not contain an identifier for the audit, instead all audits are stored as an array in a single key (actually it's two keys, `core/audit` and `core/local-audit`) so if we are notified about a change we only know something changed, but not what. So I added a `reconcileAudits` method (naming inspired by [Kubernetes](https://book.kubebuilder.io/getting-started#reconciliation-process)) which will figure out the difference between the "desired" mount table and the "actual" mount table and add or remove audit backends as needed. …
> Implement cache invalidation for audits

- command/server/config.go
- command/server/config_test_helpers.go
- vault/core.go
- vault/external_key_registry.go
- vault/external_key_registry_test.go
- vault/logical_system.go
- vault/logical_system_external_keys.go
Adds the `/sys/external-keys` endpoints described in #1320. 
Validation of configs / keys and client creation / cache management is of course missing, since we don't have the KMS interface for that yet.
I'd be happy if someone could take extra care to review the handling of transactions/locks to achieve consistency between configs and keys.. I wasn't so sure in all cases.
---
cc @phyrog @Huy-Dinh-Reply since you offered to review -- I hope you'll find that I was right saying this was 90% boilerplate 😄
> Add External Keys registry & API endpoints

- builtin/logical/pki/path_tidy.go
- changelog/1696.txt
- sdk/logical/storage.go
- sdk/logical/storage_test.go
- vault/namespace_store.go
In `logical.HandleListPage(...)`, after was being redefined each loop, leading to the previous loop iteration limits not being tracked. Add a test case for this and correctly keep track of the last seen storage entry.
This also adjusts `logical.HandleListPage(...)` to take a context and check for cancellation between outer paginated calls and before processing each entry in the batch. This will ensure we have bounded iteration in the event of another issue with `ListPage(...)`. We also validate context cancellation.
> Fix bug in tidy leading to infinite loop

- changelog/1700.txt
- command/server.go
- command/server/config.go
- command/server_test.go
- helper/profiles/config.go
- helper/profiles/config_test.go
- vault/audit.go
- vault/core.go
- vault/logical_system.go
- vault/mount.go
- website/content/docs/concepts/profiles.mdx
- website/content/docs/configuration/audit.mdx
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/self-init.mdx
- website/content/docs/rfcs/config-audit-devices.mdx
- website/content/docs/rfcs/index.mdx
- website/sidebars.ts
In solving HCSEC-2025-14 / CVE-2025-6000 / CVE-2025-54997, we opted to introduce a new flag, unsafe_allow_api_audit_creation=false, which disables audit device creation via API. This is because creating audit devices is fundamentally a service operator (and not, an internal root-token) permission: many of these audit devices allow escaping the API sandbox of the service and allow e.g., writing to arbitrary files or opening arbitrary TCP or Unix sockets.
This change introduces a new server configuration block, audit, which takes two parameters (device plugin type and desired device path), plus the regular request body of a sys/audit enable request. This allows creating in a fully-declarative manner configuration.
When device configuration fails on startup/leadership election, the server …
> Add declarative audit device creation mechanism

- vault/identity_store_oidc_test.go
This test is rather flaky in CI due to resource contention.
> Skip OIDC periodic test

- api/sys_health.go
- changelog/1730.txt
In ab940910d4edb1449f3091d9deb3c1adc9fded68, I pruned status code parameters only supported by Vault Enterprise. This means clients using OpenBao's API to talk to Vault Enterprise will receive 4xx or 5xx errors from these endpoints instead. Vault has since added more parameters, which we've opted to remap as well.
See also: https://developer.hashicorp.com/vault/api-docs/system/health
See also: https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/5733#note_2708003264
> Revert sys/health status code changes

- .github/workflows/mirror.yml
This should reduce some noise in the failing workflows.
> Don't mirror from forks

- changelog/1715.txt
- vault/core_metrics_test.go
- vault/identity_store_aliases_test.go
- vault/identity_store_entities_test.go
- vault/identity_store_test.go
- vault/identity_store_util.go
The only place where IdentityStore.db(...) is not called is when ranging over all views to collect metrics. This did not handle the unsafe cross-namespace identity behavior of using a single memdb (only available on the root namespace's view entry), leading to a nil panic.
Resolves: #1708
> Fix nil panic with unsafe_cross_namespace_identity

- vault/logical_system.go
This should help clarify some reports we've had around audit devices, as we now have a replacement in v2.4.x.
> Expand audit error message to reference config-based devices

- CHANGELOG.md
- changelog/1744.txt
- go.mod
- website/content/docs/release-notes/2-4-0.mdx
- website/content/docs/release-notes/index.mdx
- website/sidebars.ts
This release has several major improvements over v2.3.x series:
- Filtering of LIST and SCAN responses
- Configuration-based audit devices
- Configuration-based declarative self-initialization
- Delayed recovery key generation and authenticated rotation endpoints
- Inline, write-less authentication
- Static-key based unseal mechanism
See the enclosed changelog for full details.
> Release v2.4.0 GA

- api/env_test.go
Just a small typo I found along the way. We have no :snake: here
> fix: bao instead of boa (typo)

- vault/generate_root_test.go
- vault/logical_system_namespaces.go
- vault/logical_system_namespaces_rotate_test.go
- vault/logical_system_namespaces_seals_test.go
- vault/namespace_store.go
- vault/seal_manager.go
- vault/seal_test.go
- vault/storage_access.go
- vault/testing.go
This PR changes the behavior on the creation of a sealable namespace.
Changed:
- namespaces created with a seal config (sealable) are now sealed by default after creation
- moved `StorageAccess` interface to separate file `storage_access`
- tweaked tests related to namespace sealing
> Automatically seal newly created sealable namespaces

- website/content/docs/configuration/listener/tcp.mdx
Remove's the space in https://openbao.org/docs/configuration/listener/tcp/#acme-parameters so that the box is rendered correctly.
> fix(docs): remove space to render warning box correctly

- changelog/1753.txt
- vault/external_tests/identity/login_mfa_totp_test.go
- vault/login_mfa.go
- vault/request_handling.go
In creating inline authentication, I went through renaming the persistToken vs isInlineAuth, failing to correctly update the call in core.LoginMFACreateToken(...) to the latter instead of the negated former. This meant tokens created through the two-step Login MFA flow were not persistent.
This should not occur in the one-step login MFA flow. It was not caught by the existing test in
vault/external_tests/identity/login_mfa_totp_test.go, because this does not use the token after creation.
Resolves: #1752
> Fix persistence of tokens created through LoginMFA

- plugins/database/cassandra/connection_producer_test.go
- plugins/database/cassandra/test-fixtures/with_tls/cassandra.yaml
This updates `TestSelfSignedCA` to use the official Cassandra image (which is used by all other tests) instead of the one by Bitnami. This test was using the Bitnami image because it can set the required `cassandra.yaml` options via environment variables, for which the official image only provides limited support.
The new `with_tls/cassandra.yaml` file is copied 1:1 from the existing `no_tls/cassandra.yaml` file, with the `truststore`, `keystore` and `client_encryption.enabled` parameters adapted to what was previously achieved via environment variables. The alternative to providing this giant file ourselves would be a bunch of terribly hacky `sed` commands injected into the entrypoint somehow... I think duplicating the config file is still better than that.
I know pretty much _nothing_ …
> Remove dependency on bitnami/cassandra container image

- builtin/credential/jwt/path_cel_login.go
- builtin/credential/jwt/path_login.go
- changelog/1776.txt
OpenBao only allows a single login renewal handler. This works fine for the most part, but we need to begin differentiating native roles from CEL program roles, handling renewal separately.
This adds a new internal data field which we can use to disambiguate the two and wires up the pathLoginRenew handler.
---
Related: https://github.com/openbao/openbao/pull/1771#discussion_r2325072988
> Fix login renewal with CEL

- Makefile
- scripts/sync-deps-gkw.sh
- scripts/sync-deps.sh
Several of our release automation steps left off the new api/auth/jwt module along with the tools/ module. This switches to uses find statements to locate all go.mod files and adds a variant of sync-deps to update an out-of-tree go-kms-wrapping to the versions of dependencies pinned here.
> Fix bump-critical-deps & tidy-all

- vault/core.go
- vault/expiration.go
- vault/expiration_test.go
- vault/logical_system_namespaces.go
- vault/logical_system_namespaces_rotate.go
- vault/logical_system_namespaces_rotate_test.go
- vault/logical_system_rotate.go
- vault/mount.go
- vault/namespace_store.go
- vault/namespaces_oss.go
- vault/rotate.go
- vault/seal.go
- vault/seal_autoseal.go
- vault/seal_manager.go
This PR changes:
- with a core sealing (root namespace) all namespaces are being sealed, and all their related entries in `SealManager` get removed (`(*SealManager) RemoveNamespace` and `(*SealManager) Reset` methods)
- moved `unlockInformation` (and related methods) from core to `SealManager` for streamline of the unlock process
- barrier key rotation process streamlined into one logical handler for both root and other namespaces
- multiple tweaks to `SealManager`
- `(*Core) NamespaceView()` usage refactored in places where the returned view wasn't used, instead a path was only needed - added a `namespaceLogicalStoragePath(*namespace)` function
Open question:
- `(*ExpirationManager) Restore()` runs once on the unseal of the core, we probably should implement similar feature for …
> [Per-NS-Sealing] Seal Manager lifecycle adjustment

- website/content/api-docs/auth/approle.mdx
There is a missing pipe character (`|`) in the documentation. Added the character and give it a header.
> Fix missing pipe character in table column

- website/content/api-docs/secret/pki.mdx
- website/content/api-docs/secret/ssh.mdx
- website/content/api-docs/secret/transit.mdx
- website/content/api-docs/system/auth.mdx
- website/content/api-docs/system/mounts.mdx
- website/content/api-docs/system/storage/raft.mdx
- website/content/api-docs/system/tools.mdx
- website/content/docs/agent-and-proxy/agent/index.mdx
- website/content/docs/agent-and-proxy/proxy/index.mdx
- website/content/docs/audit/file.mdx
- website/content/docs/audit/index.mdx
- website/content/docs/auth/approle.mdx
- website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
- website/content/docs/auth/kubernetes.mdx
- website/content/docs/auth/ldap.mdx
- website/content/docs/auth/login-mfa/faq.mdx
- website/content/docs/commands/operator/raft.mdx
- website/content/docs/commands/pki/reissue.mdx
- website/content/docs/commands/secrets/enable.mdx
- website/content/docs/concepts/policies.mdx
- website/content/docs/configuration/index.mdx
- website/content/docs/configuration/listener/tcp.mdx
- website/content/docs/configuration/listener/unix.mdx
- website/content/docs/configuration/seal/pkcs11.mdx
- website/content/docs/platform/k8s/injector/annotations.mdx
- website/content/docs/secrets/databases/index.mdx
- website/content/docs/secrets/index.mdx
- website/content/docs/secrets/kubernetes.mdx
- website/content/docs/secrets/transit/index.mdx
- website/content/docs/upgrading/ha-upgrade.mdx
Fix indentation of `:::warning`, `:::info` and `:::danger` blocks in lists.
We have many places on our website were we do something like this:
```mdx
- `parameter_a` ...
- `parameter_b` ...
:::warning
`parameter_b` has the limitation ...
:::
- `parameter_c` ...
```
In the generated HTML this will be two unordered lists (`parameter_a`, `parameter_b`) (`parameter_c`) interrupted by a block for the warning.
If we instead indent the warning block
```mdx
- `parameter_a` ...
- `parameter_b` ...
:::warning
`parameter_b` has the limitation ...
:::
- `parameter_c` ...
```
We will get one list and the warning block will be part of the second list item, which in most cases is semantically correct.
Screenshots:
Old:
New:
Source Page: https://openbao.org/docs/secrets/transit/
This has several …
> website: fix warning/note/danger indentations

- changelog/1732.txt
- tools/go.mod
- tools/go.sum
- ui/app/models/oidc/client.js
- ui/app/models/oidc/provider.js
- vault/identity_store_oidc.go
- vault/identity_store_oidc_provider.go
- vault/identity_store_oidc_provider_test.go
- website/content/api-docs/secret/identity/oidc-provider.mdx
- website/content/docs/concepts/oidc-provider.mdx
Currently, only the [authorization code flow](https://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth) is supported. This limits OpenBao to interactive, user-centric authentication scenarios.
However, for many modern infrastructures, we also need non-interactive service-to-service authentication. For example, microservices, monitoring agents, or collectors often need to authenticate with each other securely without a user being involved.
Resolves #1727
Should this approach be accepted I will change the documentation.
> feat(OIDC-Provider): Add clientCredentialsFlow to Oidc Provider

- builtin/logical/kv/backend.go
- changelog/1872.txt
Resolves #1841
`ptypesTimestampToString` now returns back the timestamp string in `RFC3339Nano` format, as it was done, (but wrongly indicated [here](https://github.com/golang/protobuf/blob/75de7c059e36b64f01d0dd234ff2fff404ec3374/ptypes/timestamp.go#L76-L86)) by the previous version of this code fragment.
> KV engine returns timestamp strings in RFC3339Nano format

- changelog/1873.txt
- helper/identity/sentinel.go
- vault/identity_store_aliases.go
- vault/identity_store_entities.go
- vault/identity_store_groups.go
Similar to https://github.com/openbao/openbao/pull/1872 this PR changes the format of the identity system timestamps (response types) to `RFC3339Nano`, as indicated by our [documentation](https://openbao.org/api-docs/secret/identity/entity/#create-an-entity) the correct format.
(sorry for not noticing it earlier and fixing in scope of https://github.com/openbao/openbao/pull/1872)
currently:
```
curl -X POST -H "X-Vault-Token: $(bao print token)" -d '{"metadata": {"organization": "openbao","team": "openbao"},"policies": ["eng-dev", "infra-dev"]}' "http://127.0.0.1:8200/v1/identity/entity" 
{(...),"data":{"aliases":null,"id":"77ba06c3-6949-04d4-e906-876acb1e9708", (...)}
curl -H "X-Vault-Token: $(bao print token)" "http://127.0.0.1:8200/v1/identity/entity/id/77ba06c3-6949-04d4-e906-876acb1e9 …
```
> Identity subsystem returns timestamp strings in RFC3339Nano format

- vault/logical_raw.go
- vault/logical_system_rotate.go
- vault/namespace_store.go
- vault/rotate.go
- vault/seal.go
- vault/seal_autoseal.go
- vault/seal_manager.go
This PR removes `barrierByStoragePath` and related functionality from `SealManager`. This is mainly due to the realization that the same information is usually already available without the need to lock and access centralized state, with the exception of the raw backend where we can just parse the storage path, similar to what horizontal scalability does.
> Per-Namespace-Sealing: Remove barrierByStoragePath

- ui/app/models/oidc/provider.js
UI tests started failing on main following #1732, see https://github.com/openbao/openbao/commits/main. This makes it harder to spot legit CI failures because, well, green check vs red cross.
The issue seems to be incorrect formatting only, resolved via `yarn fmt:js`.
> Fix UI tests following #1732

- builtin/audit/http/backend.go
- builtin/audit/http/backend_test.go
- builtin/audit/http/testing.go
- changelog/1709.txt
- command/audit_enable_test.go
- command/commands.go
- website/content/docs/audit/file.mdx
- website/content/docs/audit/http.mdx
- website/content/docs/audit/socket.mdx
- website/sidebars.ts
This adds a new HTTP audit method, allowing collection of audit events by a remote server.
The HTTP audit device behaves like other audit devices, failing closed on failure to send the specified audit message. This is in contrast to a retry queue or batching audit device mechanism, which would also be possible but would violate the audit device contract. This keeps the implementation fairly simple. 
See also: https://gitlab.com/gitlab-org/gitlab/-/issues/470461
See also: https://gitlab.com/gitlab-com/content-sites/handbook/-/merge_requests/15328
> Add http audit method

- .github/dependabot.yml
I propose to follow the rule: **don’t touch it if it works**.
Minor and major updates often include refactors, API changes, and new features. We rely on our dependencies for stable functions, so we prefer only bug fixes and critical security updates.
This PR updates Dependabot to block minor and major updates and allow only patch updates that are at least 7 days old. Per the docs, critical security updates will still come through.
Since the website is not a critical part of our app, I configured rules to allow minor and major updates there, but only after a set minimum age.
> Delay updates for dependencies to counter supply chain attacks

- .github/workflows/test-go.yml
- builtin/logical/kv/passthrough.go
- http/logical.go
- internalshared/configutil/config.go
- physical/raft/raft.go
- vault/core.go
- vault/core_cache_invalidate.go
- vault/ha.go
- vault/request_handling.go
- website/content/docs/configuration/index.mdx
This PR:
- ~Adds a `feature_flags` stanza to the configuration~ Add a top level configuration `disable_standby_reads` (and documentation)
- ~Adds `ForwardPerformanceStandby` to kv engine "CUD" (CRUD without R) operations.~ change error wrapping in KVv1 put to support forwarding on standby.
- Fix a panic when invalidations arrive before an `activeContext` is created
- Fix requests are not forwarded, if the standby node does not have an `activeContext` (either because read replication is disabled or it is not done with post unseal).
- Fix potential nil pointer during shutdown in raft cache invalidation logic
- Actually call `HookInvalidate` (upps)
See #1550
See #1528 
> Add feature flag for read replication and fix some forwarding bugs

- http/handler.go
- http/help.go
- sdk/logical/error.go
Change the requests forwarding logic to forward requests based on substring matching in error strings. We [noticed](https://github.com/openbao/openbao/pull/1849#discussion_r2391565992) that at least in one location the `ReadOnlyError` was not "wrapped" but embedded as a substring and therefore forwarding didn't work.
Thie PR also removes the `handleRequestForwarding` handler, because it was empty anyhow (since #1674).
See #1550
See #1528 
> Read replication read only error detection
